<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PredmetSeeder2 extends Seeder
{
    public function run(): void
    {
        DB::table('predmet')->insert([
            ['predmet_id' => '502', 'naziv' => 'Upravljanje dogadjajima u turizmu', 'godina' => '2', 'smer_id' => '16'],
            ['predmet_id' => '503', 'naziv' => 'Osnovne karakteristike i vrste kartografske generalizacije', 'godina' => '2', 'smer_id' => '16'],
            ['predmet_id' => '504', 'naziv' => 'Odrzivi razvoj marginalnih podrucja Srbije', 'godina' => '2', 'smer_id' => '16'],
            ['predmet_id' => '505', 'naziv' => 'Odrzivo upravljanje zemljisnim resursima', 'godina' => '2', 'smer_id' => '16'],
            ['predmet_id' => '506', 'naziv' => 'Antropogena geomorfologija', 'godina' => '2', 'smer_id' => '16'],
            ['predmet_id' => '507', 'naziv' => 'Populaciona politika i planiranje porodice', 'godina' => '2', 'smer_id' => '16'],
            ['predmet_id' => '508', 'naziv' => 'Matematicka logika i teorija skupova', 'godina' => '1', 'smer_id' => '17'],
            ['predmet_id' => '509', 'naziv' => 'Matematicka analiza 1', 'godina' => '1', 'smer_id' => '17'],
            ['predmet_id' => '510', 'naziv' => 'Linearna algebra', 'godina' => '1', 'smer_id' => '17'],
            ['predmet_id' => '511', 'naziv' => 'Teorija brojeva i polinoma', 'godina' => '1', 'smer_id' => '17'],
            ['predmet_id' => '512', 'naziv' => 'Matematicka analiza 2', 'godina' => '1', 'smer_id' => '17'],
            ['predmet_id' => '513', 'naziv' => 'Elementarna matematika 2', 'godina' => '1', 'smer_id' => '17'],
            ['predmet_id' => '514', 'naziv' => 'Uvod u algebarske strukture', 'godina' => '1', 'smer_id' => '17'],
            ['predmet_id' => '515', 'naziv' => 'Analiticka geometrija', 'godina' => '1', 'smer_id' => '17'],
            ['predmet_id' => '516', 'naziv' => 'Matematicka analiza 3', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '517', 'naziv' => 'Uvod u numericku analizu', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '518', 'naziv' => 'Geometrija', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '519', 'naziv' => 'Elementarna matematika 1', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '520', 'naziv' => 'Konacno dimenzionalni vektorski prostori', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '521', 'naziv' => 'Matematicka analiza 4', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '522', 'naziv' => 'Teorija mera i integrala', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '523', 'naziv' => 'Uvod u verovatnocu', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '524', 'naziv' => 'Elementarna geometrija', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '525', 'naziv' => 'Metricki prostori i Riman–Stiltjesov integral', 'godina' => '2', 'smer_id' => '17'],
            ['predmet_id' => '526', 'naziv' => 'Matematicka statistika', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '527', 'naziv' => 'Uvod u kompleksnu analizu', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '528', 'naziv' => 'Uvod u topologiju', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '529', 'naziv' => 'Finansijska matematika', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '530', 'naziv' => 'Uvod u programiranje', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '531', 'naziv' => 'Uvod u diferencijalne jednacine', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '532', 'naziv' => 'Funkcionalna analiza', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '533', 'naziv' => 'Pedagogija', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '534', 'naziv' => 'Istorija i filozofija matematike', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '535', 'naziv' => 'Psihologija', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '536', 'naziv' => 'Engleski jezik', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '537', 'naziv' => 'Programski paketi u nastavi matematike', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '538', 'naziv' => 'Metodi nacrtne geometrije', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '539', 'naziv' => 'Statisticko modeliranje', 'godina' => '3', 'smer_id' => '17'],
            ['predmet_id' => '540', 'naziv' => 'Matematicka logika i teorija skupova', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '541', 'naziv' => 'Matematcka analiza 1', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '542', 'naziv' => 'Linearna algebra', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '543', 'naziv' => 'Teorija brojeva i polinoma', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '544', 'naziv' => 'Matematicka analiza 2', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '545', 'naziv' => 'Analiticka geometrija', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '546', 'naziv' => 'Elementarna matematika 1', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '547', 'naziv' => 'Programiranje 1', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '548', 'naziv' => 'Programiranje 2', 'godina' => '1', 'smer_id' => '18'],
            ['predmet_id' => '549', 'naziv' => 'Uvod u algebarske strukture', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '550', 'naziv' => 'Matematicka analiza 3', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '551', 'naziv' => 'Uvod u numericku analizu', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '552', 'naziv' => 'Konacno dimenzionalni vektorski prostori', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '553', 'naziv' => 'Elementarna matematika 2', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '554', 'naziv' => 'Matermaticka analiza 4', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '555', 'naziv' => 'Teorija mera i integrala', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '556', 'naziv' => 'Uvod u verovatnocu', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '557', 'naziv' => 'Elementarna geometrija', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '558', 'naziv' => 'Metricki prostori i Riman-Stiltjesov integral', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '559', 'naziv' => 'Finansijska matematika', 'godina' => '2', 'smer_id' => '18'],
            ['predmet_id' => '560', 'naziv' => 'Uvod u kompleksnu analizu', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '561', 'naziv' => 'Uvod u matematicku statistiku', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '562', 'naziv' => 'Uvod u topologiju', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '563', 'naziv' => 'Geometrija', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '564', 'naziv' => 'Funkcionalna analiza', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '565', 'naziv' => 'Uvod u diferencijalne jednacine', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '566', 'naziv' => 'Istorija i filozofija matematike', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '567', 'naziv' => 'Engleski jezik B1', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '568', 'naziv' => 'Statisticko modeliranje', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '569', 'naziv' => 'Metode nacrtne geometrije', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '570', 'naziv' => 'Programski paketi u nastavi matematike	', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '571', 'naziv' => 'Strucna praksa', 'godina' => '3', 'smer_id' => '18'],
            ['predmet_id' => '595', 'naziv' => 'Teorija verovatnoca', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '596', 'naziv' => 'Diferencijalne jednacine i dinamicki sistemi', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '597', 'naziv' => 'Teorija operatora', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '598', 'naziv' => 'Osnovi Furijeove analize', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '599', 'naziv' => 'Teorija fiksne tacke i primene', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '600', 'naziv' => 'Algebarske strukture', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '601', 'naziv' => 'Diferencijalna geometrija', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '602', 'naziv' => 'Parcijalne diferencijalne jednacine', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '603', 'naziv' => 'Kompleksna analiza', 'godina' => '1', 'smer_id' => '19'],
            ['predmet_id' => '604', 'naziv' => 'Neeuklidske geometrije', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '605', 'naziv' => 'Algebarska topologija', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '606', 'naziv' => 'Metodika nastave matematike', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '607', 'naziv' => 'Mera i integracija', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '608', 'naziv' => 'Teorija skupova', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '609', 'naziv' => 'Banahove algebre i spektri', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '610', 'naziv' => 'Stohasticki procesi', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '611', 'naziv' => 'Uopsteni inverzi', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '612', 'naziv' => 'Mere nekompaktnosti i primene', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '613', 'naziv' => 'Matematicka logika', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '614', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '615', 'naziv' => 'Studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '616', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '19'],
            ['predmet_id' => '617', 'naziv' => 'Teorija verovatnoca', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '618', 'naziv' => 'Multivarijaciona analiza', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '619', 'naziv' => 'Statisticki softver', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '620', 'naziv' => 'Finansijska matematika', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '621', 'naziv' => 'Diferencijalne jednacine i dinamicki sistemi', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '622', 'naziv' => 'Stohasticki procesi', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '623', 'naziv' => 'Vremenski nizovi', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '624', 'naziv' => 'Aktuarska matematika', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '625', 'naziv' => 'Parcijalne diferencijalne jednacine', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '626', 'naziv' => 'Teorija uzoraka i planiranje eksperimenata', 'godina' => '1', 'smer_id' => '20'],
            ['predmet_id' => '627', 'naziv' => 'Metode funkcionalne analize u ekonomiji', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '628', 'naziv' => 'Metodika nastave matematike', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '629', 'naziv' => 'Finansijsko modeliranje 1', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '630', 'naziv' => 'Teorija masovnog opsluzivanja', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '631', 'naziv' => 'Teorija operatora', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '632', 'naziv' => 'Teorija rizika', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '633', 'naziv' => 'Teorija odlucivanja', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '634', 'naziv' => 'Regresiona analiza u finansijama', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '635', 'naziv' => 'Stohasticki dinamicki sistemi', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '636', 'naziv' => 'Finansijsko modeliranje 2', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '637', 'naziv' => 'Statisticka kontrola kvaliteta', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '638', 'naziv' => 'Ekonometrija', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '639', 'naziv' => 'Strucna praksa ', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '640', 'naziv' => 'Studijski istrazivacki rad ', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '641', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '20'],
            ['predmet_id' => '642', 'naziv' => 'Diferencijalne jednacine i dinamicki sistemi', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '643', 'naziv' => 'Teorija operatora', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '644', 'naziv' => 'Osnovi Furijeove analize', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '645', 'naziv' => 'Teorija verovatnoca', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '646', 'naziv' => 'Parcijalne diferencijalne jednacine', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '647', 'naziv' => 'Klasicna teorijska fizika', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '648', 'naziv' => 'Teorija aproksimacija i kvadraturne formule', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '649', 'naziv' => 'Tenzorski racun', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '650', 'naziv' => 'Diferencijalna geometrija', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '651', 'naziv' => 'Stohasticki procesi', 'godina' => '1', 'smer_id' => '21'],
            ['predmet_id' => '652', 'naziv' => 'Kvantna mehanika', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '653', 'naziv' => 'Neograniceni operatori matematicke fizike', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '654', 'naziv' => 'Integralne jednacine i specijalne funkcije', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '655', 'naziv' => 'Teorija grupa i primene', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '656', 'naziv' => 'Numericko resavanje diferencijalnih jednacina', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '657', 'naziv' => 'Algebre operatora u kvantnoj mehanici', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '658', 'naziv' => 'Opsta teorija relativnosti', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '659', 'naziv' => 'Matematicki metodi nelinearne dinamike', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '660', 'naziv' => 'Simetrije u fizici', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '661', 'naziv' => 'Atomska i molekularna fizika', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '662', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '663', 'naziv' => 'Studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '664', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '21'],
            ['predmet_id' => '665', 'naziv' => 'Teorija verovatnoca', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '666', 'naziv' => 'Diferencijalne jednacine i dinamicki sistemi', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '667', 'naziv' => 'Teorija operatora', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '668', 'naziv' => 'Osnovi Furijeove analize', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '669', 'naziv' => 'Teorija fiksne tacke i primene', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '670', 'naziv' => 'Matematicka statistika', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '671', 'naziv' => 'Algebarske strukture', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '672', 'naziv' => 'Neeuklidske geometrije', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '673', 'naziv' => 'Parcijalne diferencijalne jednacine', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '674', 'naziv' => 'Kompleksna analiza', 'godina' => '1', 'smer_id' => '22'],
            ['predmet_id' => '675', 'naziv' => 'Diferencijalna geometrija', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '676', 'naziv' => 'Algebarska topologija', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '677', 'naziv' => 'Matematicka logika', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '678', 'naziv' => 'Mera i integracija', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '679', 'naziv' => 'Numericko resavanje diferencijalnih jednacina', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '680', 'naziv' => 'Teorija skupova', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '681', 'naziv' => 'Banahove algebre i spektri', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '682', 'naziv' => 'Spektralna teorija grafova', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '683', 'naziv' => 'Stohasticki procesi', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '684', 'naziv' => 'Uopsteni inverzi', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '685', 'naziv' => 'Tenzorski racun', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '686', 'naziv' => 'Mere nekompaktnosti i primene', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '687', 'naziv' => 'Kombinatorika', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '688', 'naziv' => 'Stohasticka analiza', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '689', 'naziv' => 'Teorija igara', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '690', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '691', 'naziv' => 'Predmet zavrsnog rada - studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '692', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '22'],
            ['predmet_id' => '693', 'naziv' => 'Metodika nastave matematike', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '694', 'naziv' => 'Psihologija', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '695', 'naziv' => 'Pedagogija', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '696', 'naziv' => 'Analiticke metode u elementarnoj matematici', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '697', 'naziv' => 'Odabrana poglavlja analize i algebre', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '698', 'naziv' => 'Kombinatorika', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '699', 'naziv' => 'Kompleksna analiza', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '700', 'naziv' => 'Neeuklidske geometrije', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '701', 'naziv' => 'Obrazovni softver', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '702', 'naziv' => 'Multimedijalni sistemi u nastavi matematike', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '703', 'naziv' => 'Elementi teorije brojeva', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '704', 'naziv' => 'Školska praksa 1', 'godina' => '1', 'smer_id' => '23'],
            ['predmet_id' => '705', 'naziv' => 'Diferencijalne jednacine i dinamicki sistemi', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '706', 'naziv' => 'Teorija verovatnoca', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '707', 'naziv' => 'Metodika nastave matematike u osnovnoj školi', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '708', 'naziv' => 'Metodika dodatne nastave matematike u osnovnoj školi', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '709', 'naziv' => 'Nestandardni problemi elementarne geometrije', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '710', 'naziv' => 'Teorija operatora', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '711', 'naziv' => 'Školska praksa 2', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '712', 'naziv' => 'Diskretna matematika', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '713', 'naziv' => 'Matematicka statistika i statisticko modelova', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '714', 'naziv' => 'Elementi finansijske matematike', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '715', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '716', 'naziv' => 'Predmet zavrsnog rada - studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '717', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '23'],
            ['predmet_id' => '718', 'naziv' => 'Teorija verovatnoca', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '719', 'naziv' => 'Diferencijalne jednacine i dinamicki sistemi', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '720', 'naziv' => 'Osnovi Furijeove analize', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '721', 'naziv' => 'Teorija operatora', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '722', 'naziv' => 'Algebre operatora i primene', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '723', 'naziv' => 'Kvantitativna ekologija i genetika', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '724', 'naziv' => 'Parcijalne diferencijalne jednacine', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '725', 'naziv' => 'Klasicna teorijska fizika', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '726', 'naziv' => 'Stohasticki procesi', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '727', 'naziv' => 'Strukture podataka i algoritmi', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '728', 'naziv' => 'Objektno orijentisano programiranje', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '729', 'naziv' => 'Neograniceni operatori matematicke fizike', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '730', 'naziv' => 'Metode statisticke analize', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '731', 'naziv' => 'Numericke aproksimacije i kvadraturne formule', 'godina' => '1', 'smer_id' => '24'],
            ['predmet_id' => '732', 'naziv' => 'Kvantna mehanika', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '733', 'naziv' => 'Numericka optimizacija', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '734', 'naziv' => 'Vizuelno programiranje', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '735', 'naziv' => 'Diferencijalna geometrija', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '736', 'naziv' => 'Teorija masovnog opsluzivanja', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '737', 'naziv' => 'Numericko resavanje diferencijalnih jednacina', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '738', 'naziv' => 'Tenzorski racun', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '739', 'naziv' => 'Primenjena matematicka statistika', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '740', 'naziv' => 'Baze podataka i VEB programiranje', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '741', 'naziv' => 'Osnove otvorenih kvantnih sistema', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '742', 'naziv' => 'Integralne jednacine i specijalne funkcije', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '743', 'naziv' => 'Matematicki modeli nelinearne dinamike', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '744', 'naziv' => 'Geometrijsko modelovanje', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '745', 'naziv' => 'Simetrije u fizici', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '746', 'naziv' => 'Хармонијска анализа, талисићи и примене', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '747', 'naziv' => 'Stohasticki dinamicki modeli', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '748', 'naziv' => 'Masinsko ucenje', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '749', 'naziv' => 'Atomska i molekularna fizika', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '750', 'naziv' => 'Varijacioni racun', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '751', 'naziv' => 'Matematicki modeli u biologiji i medicini', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '752', 'naziv' => 'Обрада слика и сигнала', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '753', 'naziv' => 'Teorija relativnosti', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '754', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '755', 'naziv' => 'Predmet zavrsnog rada - studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '756', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '24'],
            ['predmet_id' => '757', 'naziv' => 'Teorija verovatnoca', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '758', 'naziv' => 'Multivarijaciona analiza', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '759', 'naziv' => 'Diferencijalne jednacine i dinamicki sistemi', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '760', 'naziv' => 'Finansijska matematika', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '761', 'naziv' => 'Teorija uzoraka i planiranje eksperimenata', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '762', 'naziv' => 'Stohasticki procesi', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '763', 'naziv' => 'Analiza vremenskih nizova', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '764', 'naziv' => 'Aktuarska matematika', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '765', 'naziv' => 'Teorija igara', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '766', 'naziv' => 'Regresiona analiza', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '767', 'naziv' => 'Parcijalne diferencijalne jednacine', 'godina' => '1', 'smer_id' => '25'],
            ['predmet_id' => '768', 'naziv' => 'Metode funkcionalne analize u ekonomiji', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '769', 'naziv' => 'Statisticki softver', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '770', 'naziv' => 'Objektno orijentisano programiranje', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '771', 'naziv' => 'Finansijsko modeliranje 1', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '772', 'naziv' => 'Teorija masovnog opsluzivanja', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '773', 'naziv' => 'Numericka optimizacija', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '774', 'naziv' => 'Teorija rizika', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '775', 'naziv' => 'Teorija odlucivanja', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '776', 'naziv' => 'Ekonometrija', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '777', 'naziv' => 'Stohasticki dinamicki modeli', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '778', 'naziv' => 'Finansijsko modeliranje 2', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '779', 'naziv' => 'Statisticka kontrola kvaliteta', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '780', 'naziv' => 'Metode statisticke analize', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '781', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '782', 'naziv' => 'Predmet zavrsnog rada - studijski istrazivacki', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '783', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '25'],
            ['predmet_id' => '784', 'naziv' => 'Odabrana poglavlјa iz statistike', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '785', 'naziv' => 'Kvalitativna analiza linearnih i polulinearni', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '786', 'naziv' => 'Odabrana poglavlјa iz teorije verovatnoca', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '787', 'naziv' => 'Diferencijalna geometrija krivih i površi', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '788', 'naziv' => 'Funkcionalna analiza', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '789', 'naziv' => 'Odabrana poglavlјa algebre', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '790', 'naziv' => 'Mera i integracija', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '791', 'naziv' => 'Stohasticki procesi', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '792', 'naziv' => 'Rimanov prostor i uopstenja', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '793', 'naziv' => 'Uopsteni inverzi matrica', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '794', 'naziv' => 'Matricna analiza', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '795', 'naziv' => 'Teorija polugrupa i poluprstena', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '796', 'naziv' => 'Prostori funkcija', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '797', 'naziv' => 'Matematicka statistika', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '798', 'naziv' => 'Teorija oscilatornosti nelinearnih diferencijalnih jednačina', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '799', 'naziv' => 'Stohasticke diferencijalne jednacine	', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '800', 'naziv' => 'Prostori nesimetricne afine koneksije	', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '801', 'naziv' => 'Banahove algebre i spektri', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '802', 'naziv' => 'Nejednakost operatora i matrica', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '803', 'naziv' => 'Linearna algebra nad poluprstenima	', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '804', 'naziv' => 'Univerzalna algebra', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '805', 'naziv' => 'Teorija fiksne tacke i primene', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '806', 'naziv' => 'Odabrana poglavlјa teorija operatora', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '807', 'naziv' => 'Fredholmovi i Risovi operatori', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '808', 'naziv' => 'Uopšteni inverzi i sistemi diferencijalnih jednačina', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '809', 'naziv' => 'Uredjeni skupovi i mreze', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '810', 'naziv' => 'Metod Monte-Karlo', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '811', 'naziv' => 'Infinitezimalne deformacije', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '812', 'naziv' => 'Teorija martingala', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '813', 'naziv' => 'Studijski istrazivacki rad 1', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '814', 'naziv' => 'Studijski istrazivacki rad 2', 'godina' => '1', 'smer_id' => '26'],
            ['predmet_id' => '815', 'naziv' => 'Analiza vremenskih nizova', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '816', 'naziv' => 'Kvalitativna analiza diferencnih jednacina', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '817', 'naziv' => 'Teorija stabilnosti stohastičkih diferencijalnih jednačina', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '818', 'naziv' => 'Finansijsko modeliranje', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '819', 'naziv' => 'Geodezijska preslikavanja', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '820', 'naziv' => 'Kvantne algebarske strukture', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '821', 'naziv' => 'Odabrana poglavlјa Fredholmove teorije', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '822', 'naziv' => 'Nelinearne jednacine i sistemi', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '823', 'naziv' => 'Algebre operatora', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '824', 'naziv' => 'Matricne transformacije i nizovi', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '825', 'naziv' => 'Iterativne metode u teoriji fiksne tacke', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '826', 'naziv' => 'Matricne i operatorske jednacine', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '827', 'naziv' => 'Uopsteni inverzi operatora', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '828', 'naziv' => 'Uredjene algebarske strukture', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '829', 'naziv' => 'Regresiona analiza', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '830', 'naziv' => 'Numericko resavanje obicnih i parcijalnih dif', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '831', 'naziv' => 'Finslerovi prostori', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '832', 'naziv' => 'Vremenski nizovi u teoriji i praksi', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '833', 'naziv' => 'Pravilno promenlјive funkcije i diferencijalne jednačine', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '834', 'naziv' => 'Teorija rizika', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '835', 'naziv' => 'Numeričko rešavanje stohastičkih diferencijalnih jednačina', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '836', 'naziv' => 'Diferencijabilne mnogostrukosti', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '837', 'naziv' => 'Hilbertovi moduli', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '838', 'naziv' => 'Diferencijabilna geometrija kompleksnih i skoro kompleksnih prostora', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '839', 'naziv' => 'Perturbacije i neprekidnost uopstenih inverza', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '840', 'naziv' => 'Spektralna teorija operatora', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '841', 'naziv' => 'Glatka analiza', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '842', 'naziv' => 'Algebre, prsteni i moduli', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '843', 'naziv' => 'Fazi skupovi i sistemi', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '844', 'naziv' => 'Naucna izracunavanja', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '845', 'naziv' => 'Metode statisticke analize', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '846', 'naziv' => 'Nelinearna dinamika i teorija haosa', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '847', 'naziv' => 'Stohasticki dinamicki sistemi', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '848', 'naziv' => 'Studijski istrazivacki rad 3', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '849', 'naziv' => 'Studijski istrazivacki rad 4', 'godina' => '2', 'smer_id' => '26'],
            ['predmet_id' => '850', 'naziv' => 'Studijski istrazivacki rad 5', 'godina' => '3', 'smer_id' => '26'],
            ['predmet_id' => '851', 'naziv' => 'Studijski istrazivacki rad 6', 'godina' => '3', 'smer_id' => '26'],
            ['predmet_id' => '852', 'naziv' => 'Doktorska disertacija', 'godina' => '3', 'smer_id' => '26'],
            ['predmet_id' => '885', 'naziv' => 'Odabrana poglavlja iz statistike', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '886', 'naziv' => 'Vremenski nizovi u teoriji i praksi', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '887', 'naziv' => 'Kvalitativna analiza linearnih i polulinearni', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '888', 'naziv' => 'Numericke metode resavanja obicnih i parcijalnih diferencijalnih jednacina', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '889', 'naziv' => 'Odabrana poglavlja iz teorije verovatnoca', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '890', 'naziv' => 'Stohasticki procesi', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '891', 'naziv' => 'Diferencijalna geometrija krivih i povrsi', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '892', 'naziv' => 'Rimanov prostor i uopstenja', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '893', 'naziv' => 'Funkcionalna analiza', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '894', 'naziv' => 'Algebarske osobine generalisanih inverza', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '895', 'naziv' => 'Prostori funkcija', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '896', 'naziv' => 'Matricna analiza', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '897', 'naziv' => 'Mera i integracija', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '898', 'naziv' => 'Simbolicka i algebarska izracunavanja', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '899', 'naziv' => 'Naucno-istrazivacki rad 1', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '900', 'naziv' => 'Matematicka statistika', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '901', 'naziv' => 'Metod Monte Karlo', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '902', 'naziv' => 'Kvalitativna analiza nelinearnih diferencijalnih jednacina', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '903', 'naziv' => 'Nelinearna dinamika i teorija haosa', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '904', 'naziv' => 'Stohasticke diferencijalne jednacine', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '905', 'naziv' => 'Teorija martingala', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '906', 'naziv' => 'Prostori nesimetricne afine koneksije', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '907', 'naziv' => 'Infinitezimalne deformacije', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '908', 'naziv' => 'Banahove algebre i spektri', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '909', 'naziv' => 'Teorija fiksne tacke i primene', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '910', 'naziv' => 'Odabrana poglavlja teorija operatora', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '911', 'naziv' => 'Fredholmovi, semi-Fredholmovi i Risovi operat', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '912', 'naziv' => 'Uopsteni inverzi i sistemi diferencijalnih jednačina', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '913', 'naziv' => 'Nejednakosti operatora i matrica', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '914', 'naziv' => 'Naucna izracunavanja', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '915', 'naziv' => 'Naucno-istrazivacki rad 2', 'godina' => '1', 'smer_id' => '27'],
            ['predmet_id' => '916', 'naziv' => 'Regresiona analiza', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '917', 'naziv' => 'Pravilno promenljive funkcije i diferencijalne jednacine', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '918', 'naziv' => 'Teorija bifurkacija', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '919', 'naziv' => 'Teorija stabilnosti stohastickih diferencijalnih jednačina', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '920', 'naziv' => 'Finansijsko modeliranje', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '921', 'naziv' => 'Geodezijska preslikavanja', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '922', 'naziv' => 'Finslerovi prostori', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '923', 'naziv' => 'Matricne transformacije i nizovi', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '924', 'naziv' => 'Iterativne metode u teoriji fiksne tacke', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '925', 'naziv' => 'Matricne i operatorske jednacine i specijalne', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '926', 'naziv' => 'Numericki rang operatora – osobine i primena', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '927', 'naziv' => 'Esencijalni spektri', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '928', 'naziv' => 'Funkcionalni racun', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '929', 'naziv' => 'Uopsteni inverzi operatorа', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '930', 'naziv' => 'Operaciona istrazivanja', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '931', 'naziv' => 'Naucno-istrazivacki rad 3', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '932', 'naziv' => 'Analiza vremenskih nizova', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '933', 'naziv' => 'Metode statisticke analize', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '934', 'naziv' => 'Metematicki modeli u epidemiologiji', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '935', 'naziv' => 'Backward stohasticke diferencijalne jednacine', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '936', 'naziv' => 'Numericko resavanje stohastickih diferencijal', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '937', 'naziv' => 'Stohasticki dinamicki modeli', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '938', 'naziv' => 'Teorija rizika', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '939', 'naziv' => 'Diferencijabilne mnogostrukosti', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '940', 'naziv' => 'Diferencijalna geometrija kompleksnih i skoro kompleksnih prostora', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '941', 'naziv' => 'Mikrolokalna analiza', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '942', 'naziv' => 'Perturbacije i neprekidnost uopstenih inverza', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '943', 'naziv' => 'Spektralna mera i funkcionalni racun', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '944', 'naziv' => 'Mere nekompaktnosti i semi - Fredholmovi operatori', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '945', 'naziv' => 'Algebre, prsteni i moduli', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '946', 'naziv' => 'Spektralna teorija operatora', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '947', 'naziv' => 'Algebre operatora i Hilbertovi moduli', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '948', 'naziv' => 'Izracunavanja uopstenih inverza', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '949', 'naziv' => 'Naucno-istrazivacki rad 4', 'godina' => '2', 'smer_id' => '27'],
            ['predmet_id' => '950', 'naziv' => 'Naucni rad 1', 'godina' => '3', 'smer_id' => '27'],
            ['predmet_id' => '951', 'naziv' => 'Naucni rad 2', 'godina' => '3', 'smer_id' => '27'],
            ['predmet_id' => '952', 'naziv' => 'Doktorska disertacija', 'godina' => '3', 'smer_id' => '27'],
            ['predmet_id' => '953', 'naziv' => 'Uvod u programiranje', 'godina' => '1', 'smer_id' => '28'],
            ['predmet_id' => '954', 'naziv' => 'Diskretne strukture 1', 'godina' => '1', 'smer_id' => '28'],
            ['predmet_id' => '955', 'naziv' => 'Uvod u racunarstvo', 'godina' => '1', 'smer_id' => '28'],
            ['predmet_id' => '956', 'naziv' => 'Matematicka analiza 1', 'godina' => '1', 'smer_id' => '28'],
            ['predmet_id' => '957', 'naziv' => 'Objektno-orijentisano programiranje 1', 'godina' => '1', 'smer_id' => '28'],
            ['predmet_id' => '958', 'naziv' => 'Diskretne strukture 2', 'godina' => '1', 'smer_id' => '28'],
            ['predmet_id' => '959', 'naziv' => 'Uvod u Veb programiranje', 'godina' => '1', 'smer_id' => '28'],
            ['predmet_id' => '960', 'naziv' => 'Matematicka analiza 2', 'godina' => '1', 'smer_id' => '28'],
            ['predmet_id' => '961', 'naziv' => 'Strukture podataka i algoritmi', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '962', 'naziv' => 'Linearna algebra', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '963', 'naziv' => 'Uvod u baze podataka', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '964', 'naziv' => 'Objektno-orijentisano programiranje 2', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '965', 'naziv' => 'Dizajn i analiza algoritama', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '966', 'naziv' => 'Objektno-orijentisano programiranje 3', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '967', 'naziv' => 'Uvod u operativne sisteme', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '968', 'naziv' => 'Elektronsko izdavastvo', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '969', 'naziv' => 'Analiticka geometrija', 'godina' => '2', 'smer_id' => '28'],
            ['predmet_id' => '970', 'naziv' => 'Verovatnoca', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '971', 'naziv' => 'Teorija brojeva i polinoma', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '972', 'naziv' => 'Numericki metodi 1', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '973', 'naziv' => 'Metodika nastave informatike', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '974', 'naziv' => 'Upravlјanje projektima u IT', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '975', 'naziv' => 'Simbolicka izracunavanja', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '976', 'naziv' => 'Uvod u softversko inzenjerstvo', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '977', 'naziv' => 'Numericki metodi 2', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '978', 'naziv' => 'Open source matematicki softver', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '979', 'naziv' => 'Matematicka statistika', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '980', 'naziv' => 'Racunarske mreze', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '981', 'naziv' => 'Psihologija', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '982', 'naziv' => 'Engleski jezik 1', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '983', 'naziv' => 'Pedagogija', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '984', 'naziv' => 'Engleski jezik 2', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '985', 'naziv' => 'Asemblersko programiranje', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '986', 'naziv' => 'Web programiranje', 'godina' => '3', 'smer_id' => '28'],
            ['predmet_id' => '987', 'naziv' => 'Uvod u programiranje', 'godina' => '1', 'smer_id' => '29'],
            ['predmet_id' => '988', 'naziv' => 'Diskretne strukture 1', 'godina' => '1', 'smer_id' => '29'],
            ['predmet_id' => '989', 'naziv' => 'Uvod u racunarstvo', 'godina' => '1', 'smer_id' => '29'],
            ['predmet_id' => '990', 'naziv' => 'Matematika 1', 'godina' => '1', 'smer_id' => '29'],
            ['predmet_id' => '991', 'naziv' => 'Objektno-orijentisano programiranje 1', 'godina' => '1', 'smer_id' => '29'],
            ['predmet_id' => '992', 'naziv' => 'Diskretne strukture 2', 'godina' => '1', 'smer_id' => '29'],
            ['predmet_id' => '993', 'naziv' => 'Uvod u Veb programiranje', 'godina' => '1', 'smer_id' => '29'],
            ['predmet_id' => '994', 'naziv' => 'Matematika 2', 'godina' => '1', 'smer_id' => '29'],
            ['predmet_id' => '995', 'naziv' => 'Strukture podataka i algoritmi', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '996', 'naziv' => 'Matematika 3', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '997', 'naziv' => 'Uvod u baze podataka', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '998', 'naziv' => 'Objektno-orijentisano programiranje 2', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '999', 'naziv' => 'Dizaj i analiza algoritama', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '1000', 'naziv' => 'Uvod u operativne sisteme', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '1001', 'naziv' => 'Elektronsko izdavastvo', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '1002', 'naziv' => 'Analiticka geometrija', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '1003', 'naziv' => 'Arhitektura i organizacija racunara', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '1004', 'naziv' => 'Mikroracunarski sistemi', 'godina' => '2', 'smer_id' => '29'],
            ['predmet_id' => '1005', 'naziv' => 'Verovatnoca', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1006', 'naziv' => 'Internet pametnih uredjaja', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1007', 'naziv' => 'Numericki metodi 1', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1008', 'naziv' => 'Skript jezici', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1009', 'naziv' => 'Upravljanje projektima u IT', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1010', 'naziv' => 'Psihologija', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1011', 'naziv' => 'Pedagogija', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1012', 'naziv' => 'Paralelno i distribuirano programiranje', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1013', 'naziv' => 'Strucna/pedagoska praksa', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1014', 'naziv' => 'Racunarske mreze', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1015', 'naziv' => 'Metodika nastave informatike', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1016', 'naziv' => 'Simbolicka izracunavanja', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1017', 'naziv' => 'Numericki metodi 2', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1018', 'naziv' => 'Matricne metode i simulacije', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1019', 'naziv' => 'Matematicka statistika', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1020', 'naziv' => 'Digitalni mediji u kombinovanom ucenju', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1021', 'naziv' => 'Uvod u softversko inzenjerstvo', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1022', 'naziv' => 'Engleski jezik B1	', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1023', 'naziv' => 'Interaktivni alati za onlajn nastavu i ispite', 'godina' => '3', 'smer_id' => '29'],
            ['predmet_id' => '1024', 'naziv' => 'Teorija programskih jezika', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1025', 'naziv' => 'Dizajn softvera', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1026', 'naziv' => 'Baze podataka', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1027', 'naziv' => 'Metodika programiranja', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1028', 'naziv' => 'Opraciona istrazivanja', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1029', 'naziv' => 'Matematicka logika', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1030', 'naziv' => 'Teorija algoritama, automata i jezika', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1031', 'naziv' => 'Razvoj veb aplikacija', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1032', 'naziv' => 'Metodika elektronskog ucenja', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1033', 'naziv' => 'Numericka optimizacija', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1034', 'naziv' => 'Testiranje i metrika softvera', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1035', 'naziv' => 'Napredni kurs iz racunarskih arhitektura', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1036', 'naziv' => 'Kombinatorka i teorija grafova', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1037', 'naziv' => 'Racunarska grafika 1', 'godina' => '1', 'smer_id' => '30'],
            ['predmet_id' => '1038', 'naziv' => 'Racunarska inteligencija', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1039', 'naziv' => 'Statisticki softver', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1040', 'naziv' => 'Konstrukcija prevodioca i interpretatora', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1041', 'naziv' => 'Racunarska grafika 2', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1042', 'naziv' => 'Digitalno procesiranje signala', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1043', 'naziv' => 'Studijski istrazivacki rad 1', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1044', 'naziv' => 'Strucna/skolska praksa', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1045', 'naziv' => 'Razvoj mobilnih aplikacija', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1046', 'naziv' => 'Funkcionalno programiranje', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1047', 'naziv' => 'Kompleksne mreze', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1048', 'naziv' => 'Procesiranje jezika primenom masinskog ucenja', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1049', 'naziv' => 'Duboke neuronske mreze', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1050', 'naziv' => 'Tehnoloski praktikum napredne obrade podataka', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1051', 'naziv' => 'Paralelno i distribuirano masinsko ucenje', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1052', 'naziv' => 'Studijski istrazivacki rad 2', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1053', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '30'],
            ['predmet_id' => '1054', 'naziv' => 'Teorija programskih jezika', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1055', 'naziv' => 'Kriptografski algoritmi', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1056', 'naziv' => 'Baze podataka', 'godina' => '1', 'smer_id' => '31'],
        ]);
    }
}
