<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PredmetSeeder4 extends Seeder
{
    public function run(): void
    {
        DB::table('predmet')->insert([
            ['predmet_id' => '1557', 'naziv' => 'Optoelektronika', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1558', 'naziv' => 'Fizika materijala', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1559', 'naziv' => 'Modelovanje i simulacija fizičkih sistema', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1560', 'naziv' => 'Plazmene i laserske tehnologije', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1561', 'naziv' => 'Kvantna informatika', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1562', 'naziv' => 'Simetrije u fizici', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1563', 'naziv' => 'Nuklearna medicinska fizika', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1564', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1565', 'naziv' => 'Stručna praksa', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1566', 'naziv' => 'Studijsko istraživački rad', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1567', 'naziv' => 'Predmet master rada', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1568', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1569', 'naziv' => 'Viši kurs kvantne mehanike', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1570', 'naziv' => 'Fizika čvrstog stanja', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1571', 'naziv' => 'Fizika jonizovanih gasova', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1572', 'naziv' => 'Elementarni procesi u gasu', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1573', 'naziv' => 'Fizika plazme', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1574', 'naziv' => 'Poglavlja didaktike i metodike fizike', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1575', 'naziv' => 'Principi kvantne teorije sudara', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1576', 'naziv' => 'Nelinearna elektrodinamika plazme', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1577', 'naziv' => 'Viši kurs matematičke fizike', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1578', 'naziv' => 'Strukture atoma i molekula ', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1579', 'naziv' => 'Kosmička plazma', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1580', 'naziv' => 'Sistemi za akviziciju podataka', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1581', 'naziv' => 'Poglavlja klasične fizike', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1582', 'naziv' => 'Studijski istraživački rad 1', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1583', 'naziv' => 'Studijski istraživački rad 2', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1584', 'naziv' => 'Kinetička teorija plazme', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1585', 'naziv' => 'Sudarni i transportni procesi', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1586', 'naziv' => 'Teorija gravitacije', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1587', 'naziv' => 'Nelinearna dinamika', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1588', 'naziv' => 'Fizička merenja i senzori', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1589', 'naziv' => 'Elementi neravnotežne statističke fizike', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1590', 'naziv' => 'Metodologija pedagoškog istraživanja u nastavi fizike', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1591', 'naziv' => 'Teorija otvorenih kvantnih sistema', 'godina' => '1', 'smer_id' => '45'],
            ['predmet_id' => '1592', 'naziv' => 'Eksperimentalne metode fizike jonizovanih gasova', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1593', 'naziv' => 'Modelovanje gasnih pražnjenja', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1594', 'naziv' => 'Elektron atomski sudarni procesi', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1595', 'naziv' => 'Sudari teških čestica', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1596', 'naziv' => 'Kosmologija', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1597', 'naziv' => 'Kvantna teorija polja', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1598', 'naziv' => 'Poglavlja teorijske fizike', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1599', 'naziv' => 'Fizika elementarnih čestica', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1600', 'naziv' => 'Fizika električnih gasnih pražnjenja', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1601', 'naziv' => 'Dijagnostika gasnih pražnjenja', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1602', 'naziv' => 'Električni proboj gasova', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1603', 'naziv' => 'Fizika i tehnika solarne energetike', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1604', 'naziv' => 'Poglavlja istorije i filozofije fizike', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1605', 'naziv' => 'Fizika materijala', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1606', 'naziv' => 'Studijski istraživački rad 3', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1607', 'naziv' => 'Studijski istraživački rad 4', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1608', 'naziv' => 'Kvantna teorija na nearhimedovim i deformisanim prostorima', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1609', 'naziv' => 'Kvantnomehaničke osnove kosmologije', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1610', 'naziv' => 'Fizika obnovljivih izvora energije', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1611', 'naziv' => 'Fotonika', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1612', 'naziv' => 'Interakcija atoma sa elektromagnetnim poljem', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1613', 'naziv' => 'Modelovanje električnih proboja', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1614', 'naziv' => 'Laboratorijski eksperiment u nastavi fizike', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1615', 'naziv' => 'Primene jonizovanih gasova', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1616', 'naziv' => 'Numerička kosmologija', 'godina' => '2', 'smer_id' => '45'],
            ['predmet_id' => '1617', 'naziv' => 'Studijski istraživački rad 5', 'godina' => '3', 'smer_id' => '45'],
            ['predmet_id' => '1618', 'naziv' => 'Studijski istraživački rad 6', 'godina' => '3', 'smer_id' => '45'],
            ['predmet_id' => '1619', 'naziv' => 'Doktorske disertacija', 'godina' => '3', 'smer_id' => '45'],
            ['predmet_id' => '1620', 'naziv' => 'Viši kurs kvantne mehanike', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1621', 'naziv' => 'Nelinearna dinamika', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1622', 'naziv' => 'Poglavlja didaktike i metodike nastave fizike', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1623', 'naziv' => 'Teorija otvorenih kvantnih sistema', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1624', 'naziv' => 'Fizika jonizovanih gasova i plazme', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1625', 'naziv' => 'Fizika čvrstog stanja', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1626', 'naziv' => 'Elementi neravnotežne statističke fizike', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1627', 'naziv' => 'Viši kurs fizike atoma i molekula', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1628', 'naziv' => 'Viši kurs matematičke fizike', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1629', 'naziv' => 'Poglavlja klasične fizike', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1630', 'naziv' => 'Sudarni i transportni procesi', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1631', 'naziv' => 'IoT u sistemima za akviziciju podataka', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1632', 'naziv' => 'Studijsko istraživački rad 1', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1633', 'naziv' => 'Principi kvantne teorije sudara', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1634', 'naziv' => 'Fotonika', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1635', 'naziv' => 'Teorija gravitacije', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1636', 'naziv' => 'Metodologija pedagoškog istraživanja u fizici', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1637', 'naziv' => 'Fizika električnih gasnih pražnjenja', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1638', 'naziv' => 'Fizika obnovljivih izvora energije', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1639', 'naziv' => 'Studijsko istraživački rad 2', 'godina' => '1', 'smer_id' => '46'],
            ['predmet_id' => '1640', 'naziv' => 'Interakcija atoma sa elektromagnetnim poljem', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1641', 'naziv' => 'Kosmologija', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1642', 'naziv' => 'Kvantna teorija polja', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1643', 'naziv' => 'Poglavlja teorijske fizike', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1644', 'naziv' => 'Eksperimentalne metode fizike jonizovanih gasova', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1645', 'naziv' => 'Fizika materijala', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1646', 'naziv' => 'Teorija automatskog upravljanja', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1647', 'naziv' => 'Elektron atomski sudarni procesi', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1648', 'naziv' => 'Nelinearna optika', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1649', 'naziv' => 'Fizika elementarnih čestica', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1650', 'naziv' => 'Električni proboj gasova', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1651', 'naziv' => 'Fizika niskotemperaturne plazme', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1652', 'naziv' => 'Fizika i tehnika solarne energetike', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1653', 'naziv' => 'Studijsko istraživački rad 3', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1654', 'naziv' => 'Sudari teških čestica', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1655', 'naziv' => 'Kvantna optika', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1656', 'naziv' => 'Numerička kosmologija', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1657', 'naziv' => 'Odabrana poglavlja kosmologije', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1658', 'naziv' => 'Laboratorijski eksperiment u nastavi fizike', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1659', 'naziv' => 'Modelovanje gasnih pražnjenja', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1660', 'naziv' => 'Primene jonizovanih gasova', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1661', 'naziv' => 'Dijagnostika gasnih pražnjenja', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1662', 'naziv' => 'Fotonaponska tehnologija i primene', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1663', 'naziv' => 'Studijsko istraživački rad 4', 'godina' => '2', 'smer_id' => '46'],
            ['predmet_id' => '1664', 'naziv' => 'Studijsko istraživački rad 5', 'godina' => '3', 'smer_id' => '46'],
            ['predmet_id' => '1665', 'naziv' => 'Studijsko istraživački rad 6', 'godina' => '3', 'smer_id' => '46'],
            ['predmet_id' => '1666', 'naziv' => 'Predmet doktorske disertacije', 'godina' => '3', 'smer_id' => '46'],
            ['predmet_id' => '1667', 'naziv' => 'Doktorska disertacija', 'godina' => '3', 'smer_id' => '46'],
            ['predmet_id' => '1668', 'naziv' => 'Matematika', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1669', 'naziv' => 'Fizika', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1670', 'naziv' => 'Opšta hemija', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1671', 'naziv' => 'Primena računara u hemiji', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1672', 'naziv' => 'Istorija hemije', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1673', 'naziv' => 'Engleski jezik', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1674', 'naziv' => 'Osnove neorganske hemije', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1675', 'naziv' => 'Analitička hemija 1', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1676', 'naziv' => 'Organska  hemija 1', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1677', 'naziv' => 'Eksperimentalna organska hemija', 'godina' => '1', 'smer_id' => '47'],
            ['predmet_id' => '1678', 'naziv' => 'Analitička hemija 2', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1679', 'naziv' => 'Fizička hemija 1', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1680', 'naziv' => 'Organska hemija 2', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1681', 'naziv' => 'Struktura atoma i molekula', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1682', 'naziv' => 'Osnovi mineralogije', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1683', 'naziv' => 'Statistička obrada rezultata', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1684', 'naziv' => 'Analitička hemija 3', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1685', 'naziv' => 'Fizička hemija 2', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1686', 'naziv' => 'Hemija prelaznih metala sa koordinacionom hemijom', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1687', 'naziv' => 'Preparativna organska hemija', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1688', 'naziv' => 'Nomenklatura u organskoj hemiji', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1689', 'naziv' => 'Neorganske sirovine i materijali', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1690', 'naziv' => 'Odabrana poglavlјa volumetrijske analize', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1691', 'naziv' => 'Priprema složenih uzoraka za analizu', 'godina' => '2', 'smer_id' => '47'],
            ['predmet_id' => '1692', 'naziv' => 'Instrumentalna analitička hemija', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1693', 'naziv' => 'Hemija prirodnih proizvoda', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1694', 'naziv' => 'Osnove industrijske hemije', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1695', 'naziv' => 'Osnove hemije životne sredine', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1696', 'naziv' => 'Prehrambena neorganska hemija', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1697', 'naziv' => 'Prehrambeni aditivi', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1698', 'naziv' => 'Instrumentalne metode u organskoj hemiji', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1699', 'naziv' => 'Biohemija', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1700', 'naziv' => 'Hemodinamika zagađujućih supstanci', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1701', 'naziv' => 'Farmaceutska hemija', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1702', 'naziv' => 'Korozija i zaštita metala', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1703', 'naziv' => 'Osnovi kontrole kvaliteta u analitičkoj labortoriji', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1704', 'naziv' => 'Molekulski spektri', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1705', 'naziv' => 'Organska hemija u pojavama oko nas', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1706', 'naziv' => 'Osnove tehnologije materijala', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1707', 'naziv' => 'Prehrambena organska hemija', 'godina' => '3', 'smer_id' => '47'],
            ['predmet_id' => '1708', 'naziv' => 'Matematika', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1709', 'naziv' => 'Fizika', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1710', 'naziv' => 'Opšta hemija', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1711', 'naziv' => 'Izračunavanja u hemiji', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1712', 'naziv' => 'Primena softvera u hemiji', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1713', 'naziv' => 'Engleski jezik A2', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1714', 'naziv' => 'Osnove neorganske hemije', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1715', 'naziv' => 'Analitička hemija 1', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1716', 'naziv' => 'Organska hemija 1', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1717', 'naziv' => 'Eksperimentalna organska hemija', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1718', 'naziv' => 'Istorija hemije', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1719', 'naziv' => 'Engleski jezik B1', 'godina' => '1', 'smer_id' => '48'],
            ['predmet_id' => '1720', 'naziv' => 'Analitička hemija 2', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1721', 'naziv' => 'Fizička hemija 1', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1722', 'naziv' => 'Organska hemija 2', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1723', 'naziv' => 'Obrada rezultata u hemiji', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1724', 'naziv' => 'Nomenklatura organskih jedinjenja', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1725', 'naziv' => 'Teorija hemijske veze', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1726', 'naziv' => 'Semimikro kvalitativna analitička hemija', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1727', 'naziv' => 'Analitička hemija 3', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1728', 'naziv' => 'Fizička hemija 2', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1729', 'naziv' => 'Preparativna organska hemija', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1730', 'naziv' => 'Hemija prelaznih metala sa koordinacionom hemijom', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1731', 'naziv' => 'Fizička hemija površina', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1732', 'naziv' => 'Hemija čula', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1733', 'naziv' => 'Mineralogija sa kristalografijom', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1734', 'naziv' => 'Metode odvajanja u hemiji 1', 'godina' => '2', 'smer_id' => '48'],
            ['predmet_id' => '1735', 'naziv' => 'Hemija prirodnih proizvoda', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1736', 'naziv' => 'Osnove industrijske hemije', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1737', 'naziv' => 'Stručna praksa 1', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1738', 'naziv' => 'Fizička hemija 3', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1739', 'naziv' => 'Odabrana poglavlja volumetije', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1740', 'naziv' => 'Hemija hrane', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1741', 'naziv' => 'Osnove tehnologije materijala', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1742', 'naziv' => 'Bioneorganska hemija', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1743', 'naziv' => 'Instrumentalne metode u organskoj hemiji', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1744', 'naziv' => 'Biohemija', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1745', 'naziv' => 'Osnove hemije životne sredine', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1746', 'naziv' => 'Instrumentalna analitička hemija', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1747', 'naziv' => 'Stručna praksa 2', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1748', 'naziv' => 'Korozija i zaštita metala', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1749', 'naziv' => 'Organska hemija u pojavama oko nas', 'godina' => '3', 'smer_id' => '48'],
            ['predmet_id' => '1750', 'naziv' => 'Elektrohemija', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1751', 'naziv' => 'Savremene optičke metode analize', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1752', 'naziv' => 'Tehnike i metode karakterizacije neorganskih jedinjenja', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1753', 'naziv' => 'Dinamička stereohemija', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1754', 'naziv' => 'Bioneorganska hemija', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1755', 'naziv' => 'Hemija vode i otpadnih voda', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1756', 'naziv' => 'Savremene elektroanalitičke metode', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1757', 'naziv' => 'Organske sinteze', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1758', 'naziv' => 'Dinamička biohemija', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1759', 'naziv' => 'Industrijska hemija', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1760', 'naziv' => 'Hemija sekundarnih metabolita', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1761', 'naziv' => 'Fizičko-hemijske osnove metoda odvajanja u hemiji', 'godina' => '1', 'smer_id' => '49'],
            ['predmet_id' => '1762', 'naziv' => 'Hemometrija', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1763', 'naziv' => 'Odabrana poglavlјa organske hemije', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1764', 'naziv' => 'Teorijska neorganska hemija', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1765', 'naziv' => 'Hemija površina i koloidna hemija', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1766', 'naziv' => 'Metodologija naučno-istraživačkog rada', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1767', 'naziv' => 'Fizička hemija čvrstog stanja', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1768', 'naziv' => 'Viši kurs instrumentalnih metoda u organskoj hemiji', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1769', 'naziv' => 'Viši kurs organske hemije', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1770', 'naziv' => 'Odabrana poglavlјa fizičke hemije', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1771', 'naziv' => 'Viši kurs instrumentalnih hromatografskih metoda', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1772', 'naziv' => 'Neorganska jedinjenja u medicini i farmaciji', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1773', 'naziv' => 'Neorganska hemija 2', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1774', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1775', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '49'],
            ['predmet_id' => '1776', 'naziv' => 'Elektrohemija', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1777', 'naziv' => 'Savremene optičke metode analize', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1778', 'naziv' => 'Tehnike i metode karakterizacije neorganskih jedinjenja', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1779', 'naziv' => 'Dinamička stereohemija', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1780', 'naziv' => 'Bioneorganska hemija', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1781', 'naziv' => 'Hemija vode i otpadnih voda', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1782', 'naziv' => 'Savremene elektroanalitičke metode', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1783', 'naziv' => 'Organske sinteze', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1784', 'naziv' => 'Dinamička biohemija', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1785', 'naziv' => 'Industrijska hemija', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1786', 'naziv' => 'Hemija sekundarnih metabolita', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1787', 'naziv' => 'Fizičko-hemijske osnove metoda odvajanja u hemiji', 'godina' => '1', 'smer_id' => '50'],
            ['predmet_id' => '1788', 'naziv' => 'Metodika nastave hemije 1', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1789', 'naziv' => 'Školska praksa 1', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1790', 'naziv' => 'Školski ogledi u organskoj hemiji', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1791', 'naziv' => 'Školski ogledi u neorganskoj hemiji', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1792', 'naziv' => 'Pedagogija', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1793', 'naziv' => 'Psihologija', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1794', 'naziv' => 'Metodika nastave hemije 2', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1795', 'naziv' => 'Školska praksa 2', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1796', 'naziv' => 'Monitoring životne sredine', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1797', 'naziv' => 'Nobelove nagrade u hemiji', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1798', 'naziv' => 'Rad sa darovitim učenicima', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1799', 'naziv' => 'Aktivno učenje u hemiji', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1800', 'naziv' => 'Hemija u svakodnevnici – Etkinsovi molekuli', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1801', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1802', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '50'],
            ['predmet_id' => '1803', 'naziv' => 'Elektrohemija', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1804', 'naziv' => 'Industrijska hemija I', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1805', 'naziv' => 'Tehnike i metode karakterizacije neorganskih jedinjenja', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1806', 'naziv' => 'Hemija organskih polimera', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1807', 'naziv' => 'Analiza životnih namirnica', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1808', 'naziv' => 'Mehanizmi neorganskih reakcija', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1809', 'naziv' => 'Primenjena organska hemija', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1810', 'naziv' => 'Odabrana poglavlјa instrumentalne analize', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1811', 'naziv' => 'Industrijska hemija 2', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1812', 'naziv' => 'Hemija i tehnologija materijala', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1813', 'naziv' => 'Forenzička hemija', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1814', 'naziv' => 'Hemija voda i zemlјišta', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1815', 'naziv' => 'Neorganska jedinjenja u medicini i farmaciji	', 'godina' => '1', 'smer_id' => '51'],
            ['predmet_id' => '1816', 'naziv' => 'Primenjena hemija nemetala', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1817', 'naziv' => 'Sinteza makrokoličina organskih jedinjenja', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1818', 'naziv' => 'Kinetika i kataliza', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1819', 'naziv' => 'Neorganski materijali u industriji', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1820', 'naziv' => 'Bioanalitička hemija', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1821', 'naziv' => 'Medicinska hemija', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1822', 'naziv' => 'Industrijski procesi', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1823', 'naziv' => 'Hemija sekundarnih metabolita', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1824', 'naziv' => 'Hemija tekstilnih materijala i industrijskih boja', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1825', 'naziv' => 'Kinetičke metode analize', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1826', 'naziv' => 'Hemija u polјoprivredi', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1827', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1828', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '51'],
            ['predmet_id' => '1829', 'naziv' => 'Elektrohemija', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1830', 'naziv' => 'Industrijska hemija 1', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1831', 'naziv' => 'Tehnike i metode karakterizacije neorganskih jedinjenja', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1832', 'naziv' => 'Hemija organskih polimera', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1833', 'naziv' => 'Primenjena organska hemija', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1834', 'naziv' => 'Odabrana poglavlјa instrumentalne analize', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1835', 'naziv' => 'Industrijska hemija 2', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1836', 'naziv' => 'Hemija i tehnologija materijala', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1837', 'naziv' => 'Forenzička hemija', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1838', 'naziv' => 'Hemija voda i zemlјišta', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1839', 'naziv' => 'Neorganska jedinjenja u medicini i farmaciji', 'godina' => '1', 'smer_id' => '52'],
            ['predmet_id' => '1840', 'naziv' => 'Hemija životne sredine', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1841', 'naziv' => 'Analitička hemija životne sredine', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1842', 'naziv' => 'Hemija metala u životnoj sredini', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1843', 'naziv' => 'Zelena hemija', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1844', 'naziv' => 'Geohemija', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1845', 'naziv' => 'Biodegradacije', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1846', 'naziv' => 'Analiza toksičnih supstanci', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1847', 'naziv' => 'Organski polutanti', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1848', 'naziv' => 'Manipulacija opasnim organskim materijama', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1849', 'naziv' => 'Tehnologija vode i otpadnih voda', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1850', 'naziv' => 'Hemija gasova', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1851', 'naziv' => 'Elektrohemijske metode u hemiji životne sredine', 'godina' => '2', 'smer_id' => '52'],
            ['predmet_id' => '1852', 'naziv' => 'Viši kurs neorganske hemije', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1853', 'naziv' => 'Psihologija', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1854', 'naziv' => 'Viši kurs organske hemije', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1855', 'naziv' => 'Odabrana poglavlja instrumentalne analize', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1856', 'naziv' => 'Nobelove nagrade u hemiji', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1857', 'naziv' => 'Engleski jezik B2', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1858', 'naziv' => 'Savremene metode učenja hemije', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1859', 'naziv' => 'Neorganska jedinjenja u medicini i farmaciji', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1860', 'naziv' => 'Viši kurs biohemije', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1861', 'naziv' => 'Viši kurs industrijske hemije', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1862', 'naziv' => 'Viši kurs fizičke hemije', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1863', 'naziv' => 'Analitička zelena hemija', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1864', 'naziv' => 'Hemija u svakodnevici', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1865', 'naziv' => 'Bioanalitička hemija', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1866', 'naziv' => 'Monitoring životne sredine', 'godina' => '1', 'smer_id' => '53'],
            ['predmet_id' => '1867', 'naziv' => 'Metodika nastave hemije 1', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1868', 'naziv' => 'Školska praksa 1', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1869', 'naziv' => 'Stručna praksa', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1870', 'naziv' => 'Odabrana poglavlja organske hemije', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1871', 'naziv' => 'Farmaceutska hemija', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1872', 'naziv' => 'Mehanizmi neorganskih reakcija', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1873', 'naziv' => 'Pedagogija', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1874', 'naziv' => 'Metodika nastave hemije 2', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1875', 'naziv' => 'Školska praksa 2', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1876', 'naziv' => 'Školski ogledi 1', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1877', 'naziv' => 'Školski ogledi 2', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1878', 'naziv' => 'Metode odvajanja u hemiji 2', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1879', 'naziv' => 'Fitohemija', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1880', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1881', 'naziv' => 'Predmet master rada', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1882', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '53'],
            ['predmet_id' => '1883', 'naziv' => 'Viši kurs neorganske hemije', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1884', 'naziv' => 'Odabrana poglavlja organske hemije', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1885', 'naziv' => 'Fizičko-hemijski principi instrumentalne analize', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1886', 'naziv' => 'Metodologija naučnoistraživačkog rada', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1887', 'naziv' => 'Engleski jezik B2', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1888', 'naziv' => 'Botanika', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1889', 'naziv' => 'Hemija vode i otpadnih voda', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1890', 'naziv' => 'Kinetika i kataliza', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1891', 'naziv' => 'Viši kurs biohemije', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1892', 'naziv' => 'Viši kurs industrijske hemije', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1893', 'naziv' => 'Viši kurs fizičke hemije', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1894', 'naziv' => 'Primena savremenih instrumentalnih metoda u analitičkoj hemiji', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1895', 'naziv' => 'Geohemija', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1896', 'naziv' => 'Bioanalitička hemija', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1897', 'naziv' => 'Metode odvajanja u hemiji 2', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1898', 'naziv' => 'Fitohemija', 'godina' => '1', 'smer_id' => '54'],
            ['predmet_id' => '1899', 'naziv' => 'Organska sterohemija', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1900', 'naziv' => 'Hemometrija', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1901', 'naziv' => 'Karakterizacija neorganskih jedinjenja', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1902', 'naziv' => 'Stručna praksa', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1903', 'naziv' => 'Odabrana poglavlja fizičke hemije', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1904', 'naziv' => 'Farmaceutska hemija', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1905', 'naziv' => 'Analiza toksičnih supstanci', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1906', 'naziv' => 'Mehanizmi neorganskih reakcija', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1907', 'naziv' => 'Organske sinteze', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1908', 'naziv' => 'Računarska hemija', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1909', 'naziv' => 'Viši kurs instrumentalnih metoda u organskoj hemiji', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1910', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1911', 'naziv' => 'Predmet master rada', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1912', 'naziv' => 'Hemija površina i koloidna hemija', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1913', 'naziv' => 'Medicinska hemija', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1914', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '54'],
            ['predmet_id' => '1915', 'naziv' => 'Viši kurs organske hemije', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1916', 'naziv' => 'Odabrana poglavlja neorganske hemije', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1917', 'naziv' => 'Savremene metode instrumentalne analize', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1918', 'naziv' => 'Industrijska hemija 1', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1919', 'naziv' => 'Osnove menadžmenta', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1920', 'naziv' => 'Engleski jezik B2', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1921', 'naziv' => 'Poljoprivredna hemija', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1922', 'naziv' => 'Viši kurs biohemije', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1923', 'naziv' => 'Metodologija naučnoistraživačkog rada', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1924', 'naziv' => 'Organski polutanti', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1925', 'naziv' => 'Neorganska jedinjenja u industriji', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1926', 'naziv' => 'Analitička hemija životne sredine', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1927', 'naziv' => 'Viši kurs fizičke hemije', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1928', 'naziv' => 'Industrijska hemija 2', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1929', 'naziv' => 'Viši kurs hemije životne sredine', 'godina' => '1', 'smer_id' => '55'],
            ['predmet_id' => '1930', 'naziv' => 'Karakterizacija hemijskih jedinjenja', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1931', 'naziv' => 'Upravljanje kvalitetom u laboratoriji', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1932', 'naziv' => 'Upravljanje hemikalijama', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1933', 'naziv' => 'Standardi kvaliteta u laboratoriji', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1934', 'naziv' => 'Primenjena organska hemija', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1935', 'naziv' => 'Hemija tekstilnih materijala i industrijskih boja', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1936', 'naziv' => 'Tehnologija vode i otpadnih voda', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1937', 'naziv' => 'Analiza životnih namirnica', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1938', 'naziv' => 'Hemija i tehnologija materijala', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1939', 'naziv' => 'Forenzička hemija', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1940', 'naziv' => 'Hemija vode i zemljišta', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1941', 'naziv' => 'Industrijski procesi', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1942', 'naziv' => 'Stručna praksa', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1943', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1944', 'naziv' => 'Predmet master rada', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1945', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '55'],
            ['predmet_id' => '1946', 'naziv' => 'Odabrana poglavlјa tehnika i metoda karakterizacija neorganskih jedinjenja', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1947', 'naziv' => 'Instrumentalne metode analize odabranih grupa organskih jedinjenja', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1948', 'naziv' => 'Izolovanje sekundarnih metabolita', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1949', 'naziv' => 'Hemija površinskih procesa', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1950', 'naziv' => 'Hemijska mikrobiologija', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1951', 'naziv' => 'Odabrana poglavlјa hemije životne sredine', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1952', 'naziv' => 'Površinski aktivne materije', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1953', 'naziv' => 'Ravnoteže u hemiji', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1954', 'naziv' => 'Odabrana poglavlјa iz optičkih i srodnih metoda hemijske analize', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1955', 'naziv' => 'Atomska spektroskopija', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1956', 'naziv' => 'Fizička organska hemija', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1957', 'naziv' => 'Studijski istraživački rad 1', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1958', 'naziv' => 'Odabrana poglavlјa geohemije', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1959', 'naziv' => 'Monitoring zagađujućih supstanci', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1960', 'naziv' => 'Hemija boja', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1961', 'naziv' => 'Odabrana poglavlјa prečišćavanja i dezinfekci', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1962', 'naziv' => 'Odabrana poglavlјa elektrohemijskih metode analize', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1963', 'naziv' => 'Instrumentalna analiza 1', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1964', 'naziv' => 'Fizičko-hemijske metode ispitivanja ravnoteža u kompleksirajućim sredinama', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1965', 'naziv' => 'Identifikacija prirodnih proizvoda', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1966', 'naziv' => 'Savremene organske sinteze', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1967', 'naziv' => 'Hemija bilјnih pigmenata', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1968', 'naziv' => 'Studijski istraživački rad 2', 'godina' => '1', 'smer_id' => '56'],
            ['predmet_id' => '1969', 'naziv' => 'Odabrana poglavlјa neorganske hemije', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1970', 'naziv' => 'Odabrana poglavlјa teorijske hemije', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1971', 'naziv' => 'Asimetrične sinteze', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1972', 'naziv' => 'Eksperimentalna biohemija', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1973', 'naziv' => 'Dvodimenzionalna nuklearna magnetna rezonanca', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1974', 'naziv' => 'Nanostrukturni materijali', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1975', 'naziv' => 'Metrika boja', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1976', 'naziv' => 'Savremeni postupci prečišćavanja vode', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1977', 'naziv' => 'Metode odvajanja', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1978', 'naziv' => 'Kinetičke metode analize', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1979', 'naziv' => 'Odabrana poglavlјa fizičke hemije', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1980', 'naziv' => 'Studijski istraživački rad 3', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1981', 'naziv' => 'Odabrana poglavlјa bioneorganske hemije', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1982', 'naziv' => 'Odabrana poglavlјa supramolekulske hemije i hemije makromolekula', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1983', 'naziv' => 'Sekundarni metaboliti kao biomarkeri', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1984', 'naziv' => 'Molekulsko modelovanje u organskoj hemiji', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1985', 'naziv' => 'Remedijacione tehnologije', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1986', 'naziv' => 'Huminske supstance u životnoj sredini', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1987', 'naziv' => 'Instrumentalna analiza 2', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1988', 'naziv' => 'Molekulska spektroskopija', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1989', 'naziv' => 'Konformaciona analiza biomakromolekula', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1990', 'naziv' => 'Odabrana poglavlјa u primeni organskih reagen', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1991', 'naziv' => 'Studijski istraživački rad 4', 'godina' => '2', 'smer_id' => '56'],
            ['predmet_id' => '1992', 'naziv' => 'Studijski istraživački rad 5', 'godina' => '3', 'smer_id' => '56'],
            ['predmet_id' => '1993', 'naziv' => 'Doktorska  disertacija', 'godina' => '3', 'smer_id' => '56'],
            ['predmet_id' => '1994', 'naziv' => 'Instrumentalne metode analize odabranih grupa organskih jedinjenja', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '1995', 'naziv' => 'Izolovanje sekundarnih metabolita', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '1996', 'naziv' => 'Hemijska mikrobiologija', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '1997', 'naziv' => 'Fizička organska hemija', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '1998', 'naziv' => 'Odabrana poglavlјa tehnika i metoda karakterizacije neorganskih jedinjenja', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '1999', 'naziv' => 'Odabrana poglavlja geohemije', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2000', 'naziv' => 'Ravnoteže u hemiji', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2001', 'naziv' => 'Atomska spektroskopija', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2002', 'naziv' => 'Molekulska spektroskopija', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2003', 'naziv' => 'Remedijacione tehnologije', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2004', 'naziv' => 'Hemija boja', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2005', 'naziv' => 'Identifikacija prirodnih proizvoda', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2006', 'naziv' => 'Savremene organske sinteze', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2007', 'naziv' => 'Hemija biljnih pigmenata', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2008', 'naziv' => 'Odabrana poglavlja opšte hemije', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2009', 'naziv' => 'Odabrana poglavlja neorganske hemije', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2010', 'naziv' => 'Instrumentalna analiza 1', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2011', 'naziv' => 'Savremene hromatografske metode', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2012', 'naziv' => 'Odabrana poglavlja metoda odvajanja u hemiji', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2013', 'naziv' => 'Savremene elektroanalitičke metode analize', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2014', 'naziv' => 'Metrika boja', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2015', 'naziv' => 'Odabrana poglavlja hemije životne sredine', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2016', 'naziv' => 'Nanostrukturni materijali', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2017', 'naziv' => 'Studijski istraživački rad 1', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2018', 'naziv' => 'Studijski istraživački rad 2', 'godina' => '1', 'smer_id' => '57'],
            ['predmet_id' => '2019', 'naziv' => 'Asimetrične sinteze', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2020', 'naziv' => 'Eksperimentalna biohemija', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2021', 'naziv' => 'Dvodimenzionalna nuklearna magnetna rezonanca', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2022', 'naziv' => 'Odabrana poglavlja koordinacione hemije', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2023', 'naziv' => 'Odabrana poglavlja primenjene neorganske hemije', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2024', 'naziv' => 'Odabrana poglavlja iz savremenih metoda instrumentalne analize', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2025', 'naziv' => 'Kliničko-hemijske metode analize', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2026', 'naziv' => 'Ravnoteža i kinetika procesa', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2027', 'naziv' => 'Odabrana poglavlja fizičke hemije', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2028', 'naziv' => 'Površinski aktivne materije', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2029', 'naziv' => 'Monitoring zagađujućih supstanci', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2030', 'naziv' => 'Hemija površinskih procesa', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2031', 'naziv' => 'Naučno istraživački rad 1', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2032', 'naziv' => 'Odabrana poglavlja supramolekulske hemije i hemije makromolekula', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2033', 'naziv' => 'Sekundarni metaboliti kao biomarkeri', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2034', 'naziv' => 'Molekulsko modelovanje u organskoj hemiji', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2035', 'naziv' => 'Konformaciona analiza biomakromolekula', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2036', 'naziv' => 'Odabrana poglavlja bioneorganske hemije', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2037', 'naziv' => 'Multidisciplinarni aspekti neorganske hemije', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2038', 'naziv' => 'Instrumentalna analiza 2', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2039', 'naziv' => 'Viši kurs hemometrije', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2040', 'naziv' => 'Analitika organskih polutanata', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2041', 'naziv' => 'Savremeni postupci prečišćavanja vode', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2042', 'naziv' => 'Huminske supstance u životnoj sredini', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2043', 'naziv' => 'Odabrana poglavlja prečišćavanja i dezinfekcije vode', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2044', 'naziv' => 'Naučno istraživački rad 2', 'godina' => '2', 'smer_id' => '57'],
            ['predmet_id' => '2045', 'naziv' => 'Samostalni istraživački rad', 'godina' => '3', 'smer_id' => '57'],
            ['predmet_id' => '2046', 'naziv' => 'Predmet doktorske disertacije', 'godina' => '3', 'smer_id' => '57'],
            ['predmet_id' => '2047', 'naziv' => 'Doktorska disertacija', 'godina' => '3', 'smer_id' => '57'],
            ['predmet_id' => '2048', 'naziv' => 'Veb programiranje', 'godina' => '2', 'smer_id' => '29'],
        ]);
    }
}
