<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PredmetSeeder3 extends Seeder
{
    public function run(): void
    {
        DB::table('predmet')->insert([
            ['predmet_id' => '1057', 'naziv' => 'Metodika programiranja', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1058', 'naziv' => 'Operaciona istrazivanja', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1059', 'naziv' => 'Matematicka logika', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1060', 'naziv' => 'Teorija algoritama, automata i jezika', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1061', 'naziv' => 'Teorija informacija i kodiranje', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1062', 'naziv' => 'Metodika elektronskog ucenja', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1063', 'naziv' => 'Numericka optimizacija', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1064', 'naziv' => 'Testiranje i metrika softvera', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1065', 'naziv' => 'Napredni kurs iz racunarskih arhitektura', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1066', 'naziv' => 'Kombinatorka i teorija grafova', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1067', 'naziv' => 'Racunarska grafika 1', 'godina' => '1', 'smer_id' => '31'],
            ['predmet_id' => '1068', 'naziv' => 'Inteligentna obrada podataka', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1069', 'naziv' => 'Statisticki softver', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1070', 'naziv' => 'Fazi sistemi', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1071', 'naziv' => 'Digitalno procesiranje signala', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1072', 'naziv' => 'Studijski istrazivacki rad 1', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1073', 'naziv' => 'Multimedijalni informacioni sistemi', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1074', 'naziv' => 'Sistemi zasnovani na znanju', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1075', 'naziv' => 'Teorija odlucivanja', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1076', 'naziv' => 'Procesiranje jezika primenom masinskog ucenja', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1077', 'naziv' => 'Duboke neuronske mreze', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1078', 'naziv' => 'Paralelno i distribuirano masinsko ucenje', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1079', 'naziv' => 'Studijski istrazivacki rad 2', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1080', 'naziv' => 'Strucna/skolska praksa', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1081', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '31'],
            ['predmet_id' => '1082', 'naziv' => 'Mašinsko učenje i veštačka inteligencija', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1083', 'naziv' => 'Algoritmi optimizacije u mašinskom učenju', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1084', 'naziv' => 'Statističke osnove inteligentne obrade podataka', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1085', 'naziv' => 'Kombinatorika i teorija grafova', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1086', 'naziv' => 'Bezbednost informacija i veštačka inteligencija', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1087', 'naziv' => 'Probabilistički automati', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1088', 'naziv' => 'Bajesova analiza podataka', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1089', 'naziv' => 'Teorija informacija u mašinskom učenju', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1090', 'naziv' => 'Tehnološki praktikum napredne obrade podataka', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1091', 'naziv' => 'Veštačke neuronske mreže', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1092', 'naziv' => 'Obrada velikih skupova podataka', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1093', 'naziv' => 'Mašinsko učenje i veštačka inteligencija u robotici', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1094', 'naziv' => 'Konstrukcija prevodioca i interpretera', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1095', 'naziv' => 'Testiranje i metrika softvera', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1096', 'naziv' => 'Probabilistički grafički modeli', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1097', 'naziv' => 'Digitalna obrada slika', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1098', 'naziv' => 'Metode statističke analize', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1099', 'naziv' => 'Napredni kurs iz računarskih arhitektura', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1100', 'naziv' => 'Računarska grafika 1', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1101', 'naziv' => 'Virtuelne učionice', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1102', 'naziv' => 'Paralelno i distribuirano mašinsko učenje', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1103', 'naziv' => 'Regresiona analiza podataka', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1104', 'naziv' => 'Razvoj platformi za mešovito učenje', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1105', 'naziv' => 'Napredni dizajn i analiza algoritama', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1106', 'naziv' => 'Aproksimativno rasuđivanje', 'godina' => '1', 'smer_id' => '32'],
            ['predmet_id' => '1107', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1108', 'naziv' => 'Softverske platforme i programski jezici za mašinsko učenje i veštačku inteligenciju', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1109', 'naziv' => 'Učenje pojačavanjem', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1110', 'naziv' => 'Stručna/pedagoška praksa', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1111', 'naziv' => 'Statistički softver', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1112', 'naziv' => 'Funkcionalno programiranje', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1113', 'naziv' => 'Рачунарска графика 2', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1114', 'naziv' => 'Fazi sistemi', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1115', 'naziv' => 'Analiza vremenskih nizova', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1116', 'naziv' => 'Nenadgledano mašinsko učenje', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1117', 'naziv' => 'Matematička logika', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1118', 'naziv' => 'Kompleksne mreže', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1119', 'naziv' => 'Sistemi zasnovani na znanju', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1120', 'naziv' => 'Teorija odlučivanja', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1121', 'naziv' => 'Primena veštačke inteligencije u biomedicini', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1122', 'naziv' => 'Obrada prirodnih jezika', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1123', 'naziv' => 'Digitalna obrada signala', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1124', 'naziv' => 'Didaktičko-informatičke inovacije', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1125', 'naziv' => 'Master rad - studijski istraživački rad', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1126', 'naziv' => 'Master rad - izrada i odbrana', 'godina' => '2', 'smer_id' => '32'],
            ['predmet_id' => '1127', 'naziv' => 'Mašinsko učenje i veštačka inteligencija', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1128', 'naziv' => 'Dizajn softvera', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1129', 'naziv' => 'Baze podataka', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1130', 'naziv' => 'Tehnološki praktikum napredne obrade podataka', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1131', 'naziv' => 'Metodika programiranja', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1132', 'naziv' => 'Operaciona istraživanja', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1133', 'naziv' => 'Numerička optimizacija', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1134', 'naziv' => 'Razvoj veb aplikacija', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1135', 'naziv' => 'Teorija programskih jezika', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1136', 'naziv' => 'Mašinsko učenje i veštačka inteligencija u robotici', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1137', 'naziv' => 'Konstrukcija prevodioca i interpretera', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1138', 'naziv' => 'Testiranje i metrika softvera', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1139', 'naziv' => 'Probabilistički grafički modeli', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1140', 'naziv' => 'Digitalna obrada slika', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1141', 'naziv' => 'Metode statističke analize', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1142', 'naziv' => 'Napredni kurs iz računarskih arhitektura', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1143', 'naziv' => 'Računarska grafika 1', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1144', 'naziv' => 'Virtuelne učionice', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1145', 'naziv' => 'Paralelno i distribuirano mašinsko učenje', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1146', 'naziv' => 'Regresiona analiza podataka', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1147', 'naziv' => 'Razvoj platformi za mešovito učenje', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1148', 'naziv' => 'Napredni dizajn i analiza algoritama', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1149', 'naziv' => 'Aproksimativno rasuđivanje', 'godina' => '1', 'smer_id' => '33'],
            ['predmet_id' => '1150', 'naziv' => 'Teorija algoritama, automata i jezika', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1151', 'naziv' => 'Razvoj mobilnih aplikacija', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1152', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1153', 'naziv' => 'Stručna/pedagoška praksa', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1154', 'naziv' => 'Statistički softver', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1155', 'naziv' => 'Funkcionalno programiranje', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1156', 'naziv' => 'Računarska grafika 2', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1157', 'naziv' => 'Fazi sistemi', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1158', 'naziv' => 'Analiza vremenskih nizova', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1159', 'naziv' => 'Nenadgledano mašinsko učenje', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1160', 'naziv' => 'Matematička logika', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1161', 'naziv' => 'Kompleksne mreže', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1162', 'naziv' => 'Sistemi zasnovani na znanju', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1163', 'naziv' => 'Teorija odlučivanja', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1164', 'naziv' => 'Primena veštačke inteligencije u biomedicini', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1165', 'naziv' => 'Obrada prirodnih jezika', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1166', 'naziv' => 'Digitalna obrada signala', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1167', 'naziv' => 'Didaktičko-informatičke inovacije', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1168', 'naziv' => 'Master rad - studijski istraživački rad', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1169', 'naziv' => 'Master rad - izrada i odbrana', 'godina' => '2', 'smer_id' => '33'],
            ['predmet_id' => '1170', 'naziv' => 'Mašinsko učenje i veštačka inteligencija', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1171', 'naziv' => 'Bezbednost informacija', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1172', 'naziv' => 'Baze podataka', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1173', 'naziv' => 'Tehnološki praktikum napredne obrade podataka', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1174', 'naziv' => 'Metodika programiranja', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1175', 'naziv' => 'Operaciona istraživanja', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1176', 'naziv' => 'Numerička optimizacija', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1177', 'naziv' => 'Multimedijalni informacioni sistemi', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1178', 'naziv' => 'Teorija programskih jezika', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1179', 'naziv' => 'Mašinsko učenje i veštačka inteligencija u robotici', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1180', 'naziv' => 'Konstrukcija prevodioca i interpretera', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1181', 'naziv' => 'Testiranje i metrika softvera', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1182', 'naziv' => 'Probabilistički grafički modeli', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1183', 'naziv' => 'Digitalna obrada slika', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1184', 'naziv' => 'Metode statističke analize', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1185', 'naziv' => 'Napredni kurs iz računarskih arhitektura', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1186', 'naziv' => 'Računarska grafika 1', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1187', 'naziv' => 'Virtuelne učionice', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1188', 'naziv' => 'Paralelno i distribuirano mašinsko učenje', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1189', 'naziv' => 'Regresiona analiza podataka', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1190', 'naziv' => 'Razvoj platformi za mešovito učenje', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1191', 'naziv' => 'Napredni dizajn i analiza algoritama', 'godina' => '1', 'smer_id' => '34'],
            ['predmet_id' => '1192', 'naziv' => 'Statistički softver', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1193', 'naziv' => 'Funkcionalno programiranje', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1194', 'naziv' => 'Računarska grafika 2', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1195', 'naziv' => 'Fazi sistemi', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1196', 'naziv' => 'Analiza vremenskih nizova', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1197', 'naziv' => 'Nenadgledano mašinsko učenje', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1198', 'naziv' => 'Matematička logika', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1199', 'naziv' => 'Kompleksne mreže', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1200', 'naziv' => 'Sistemi zasnovani na znanju', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1201', 'naziv' => 'Teorija odlučivanja', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1202', 'naziv' => 'Primena veštačke inteligencije u biomedicini', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1203', 'naziv' => 'Obrada prirodnih jezika', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1204', 'naziv' => 'Digitalna obrada signala', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1205', 'naziv' => 'Didaktičko-informatičke inovacije', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1206', 'naziv' => 'Master rad - studijski istraživački rad', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1207', 'naziv' => 'Master rad - izrada i odbrana', 'godina' => '2', 'smer_id' => '34'],
            ['predmet_id' => '1208', 'naziv' => 'Metodologija naučno-istraživačkog rada', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1209', 'naziv' => 'Formalni jezici, automati i izračunlјivost', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1210', 'naziv' => 'Mašinsko učenje', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1211', 'naziv' => 'Odabrana poglavlјa iz statistike', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1212', 'naziv' => 'Simbolička i algebarska izračunavanja', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1213', 'naziv' => 'Uređeni skupovi i mreže', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1214', 'naziv' => 'Napredni kurs iz numeričke optimizacije', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1215', 'naziv' => 'Fazi skupovi i sistemi', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1216', 'naziv' => 'Operaciona istraživanja', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1217', 'naziv' => 'Veštačke neuronske mreže', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1218', 'naziv' => 'Algebarska kombinatorika', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1219', 'naziv' => 'Teorija polugrupa i poluprstena', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1220', 'naziv' => 'Naučna izračunavanja', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1221', 'naziv' => 'Studijski istraživački rad 1', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1222', 'naziv' => 'Studijski istraživački rad 2', 'godina' => '1', 'smer_id' => '35'],
            ['predmet_id' => '1223', 'naziv' => 'Algebarska teorija automata i formalnih jezika', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1224', 'naziv' => 'Izračunavanja uopštenih inverza', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1225', 'naziv' => 'Algebarska teorija grafova', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1226', 'naziv' => 'Inteligentna obrada teksta', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1227', 'naziv' => 'Odabrana poglavlјa iz algebre', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1228', 'naziv' => 'Primena spektara grafova u računarstvu', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1229', 'naziv' => 'Prirodna izračunavanja', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1230', 'naziv' => 'Objektno-orijentisana analiza i dizajn', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1231', 'naziv' => 'Dizajn i analiza algoritama', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1232', 'naziv' => 'Obrada slika i animacija', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1233', 'naziv' => 'Inteligentna obrada podataka i prepoznavanje ', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1234', 'naziv' => 'Odabrana poglavlјa molekularne biologije', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1235', 'naziv' => 'Kvantna informatika i kvantno računanje', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1236', 'naziv' => 'Implementacija i primena automata', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1237', 'naziv' => 'Dizajn i analiza algoritama 2', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1238', 'naziv' => 'Studijski istraživački rad 3', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1239', 'naziv' => 'Studijski istraživački rad 4', 'godina' => '2', 'smer_id' => '35'],
            ['predmet_id' => '1240', 'naziv' => 'Studijski istraživački rad 5', 'godina' => '3', 'smer_id' => '35'],
            ['predmet_id' => '1241', 'naziv' => 'Studijski istraživački rad 6', 'godina' => '3', 'smer_id' => '35'],
            ['predmet_id' => '1242', 'naziv' => 'Metodologija naučnoistraživačkog rada', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1243', 'naziv' => 'Formalni jezici, automati i izračunljivost', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1244', 'naziv' => 'Mašinsko učenje', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1245', 'naziv' => 'Odabrana poglavlja iz statistike', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1246', 'naziv' => 'Simbolička i algebarska izračunavanja', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1247', 'naziv' => 'Mreže i uređene algebarske strukture', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1248', 'naziv' => 'Napredni kurs iz numeričke optimizacije', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1249', 'naziv' => 'Učenje probabilističkih grafičkih modela', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1250', 'naziv' => 'Vizualizacija naučnih podataka', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1251', 'naziv' => 'Studijski istraživački rad 1', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1252', 'naziv' => 'Studijski istraživački rad 2', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1253', 'naziv' => 'Fazi skupovi i sistemi', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1254', 'naziv' => 'Operaciona istraživanja', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1255', 'naziv' => 'Veštačke neuronske mreže', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1256', 'naziv' => 'Algebarska kombinatorika', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1257', 'naziv' => 'Teorija polugrupa i poluprstena', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1258', 'naziv' => 'Naučna izračunavanja', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1259', 'naziv' => 'Objektno-orijentisana analiza i dizajn', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1260', 'naziv' => 'Napredne tehnike računarske grafike', 'godina' => '1', 'smer_id' => '36'],
            ['predmet_id' => '1261', 'naziv' => 'Algebarska teorija automata i formalnih jezika', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1262', 'naziv' => 'Rekurentne neuronske mreže u numeričkoj linearnoj algebri', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1263', 'naziv' => 'Algebarska teorija grafova', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1264', 'naziv' => 'Inteligentna obrada teksta', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1265', 'naziv' => 'Kvantitativni automati', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1266', 'naziv' => 'Primena spektara grafova u računarstvu', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1267', 'naziv' => 'Dizajn i analiza algoritama', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1268', 'naziv' => 'Kvantno procesiranje informacija', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1269', 'naziv' => 'Studijski istraživački rad 3', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1270', 'naziv' => 'Studijski istraživački rad 4', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1271', 'naziv' => 'Prirodna izračunavanja', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1272', 'naziv' => 'Obrada slika i animacija', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1273', 'naziv' => 'Inteligentna obrada podataka i prepoznavanje uzoraka', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1274', 'naziv' => 'Odabrana poglavlja molekularne biologije', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1275', 'naziv' => 'Kvantno računarstvo', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1276', 'naziv' => 'Implementacija i primena automata', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1277', 'naziv' => 'Dizajn i analiza algoritama 2', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1278', 'naziv' => 'Analiza socijalnih mreža', 'godina' => '2', 'smer_id' => '36'],
            ['predmet_id' => '1279', 'naziv' => 'Doktorska disertacija – naučno-istraživački rad 1', 'godina' => '3', 'smer_id' => '36'],
            ['predmet_id' => '1280', 'naziv' => 'Doktorska disertacija – naučno-istraživački rad 2', 'godina' => '3', 'smer_id' => '36'],
            ['predmet_id' => '1281', 'naziv' => 'Doktorska disertacija – izrada i odbrana', 'godina' => '3', 'smer_id' => '36'],
            ['predmet_id' => '1282', 'naziv' => 'Mehanika', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1283', 'naziv' => 'Matematika 1', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1284', 'naziv' => 'Metrologija i obrada rezultata merenja', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1285', 'naziv' => 'Laboratorijski praktikum 1', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1286', 'naziv' => 'Programiranje u fizici', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1287', 'naziv' => 'Termodinamika i molekularna fizika', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1288', 'naziv' => 'Matematika 2', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1289', 'naziv' => 'Laboratorijski praktikum 2', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1290', 'naziv' => 'Hemija', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1291', 'naziv' => 'Engleski jezik', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1292', 'naziv' => 'Psihologija', 'godina' => '1', 'smer_id' => '37'],
            ['predmet_id' => '1293', 'naziv' => 'Elektromagnetizam', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1294', 'naziv' => 'Matematika 3', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1295', 'naziv' => 'Osnove matematičke fizike', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1296', 'naziv' => 'Laboratorijski praktikum 3', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1297', 'naziv' => 'Osnove računarstva', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1298', 'naziv' => 'Uvod u objektno orijentisano programiranje', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1299', 'naziv' => 'Optika', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1300', 'naziv' => 'Osnove teorijske mehanike', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1301', 'naziv' => 'Matematička fizika', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1302', 'naziv' => 'Laboratorijski praktikum 4', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1303', 'naziv' => 'Fizika životne sredine', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1304', 'naziv' => 'Matematika 4', 'godina' => '2', 'smer_id' => '37'],
            ['predmet_id' => '1305', 'naziv' => 'Osnove statističke fizike', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1306', 'naziv' => 'Osnove atomske i molekularne fizike', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1307', 'naziv' => 'Eksperimentalne metode u fizici', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1308', 'naziv' => 'Specijalna teorija relativnosti', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1309', 'naziv' => 'Fizika atmosfere', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1310', 'naziv' => 'Fizički izvori štetnosti', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1311', 'naziv' => 'Oscilacije i talasi', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1312', 'naziv' => 'Osnove elektrodinamike', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1313', 'naziv' => 'Osnove kvantne mehanike', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1314', 'naziv' => 'Osnove fizike čvrstog stanja', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1315', 'naziv' => 'Nuklearna fizika', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1316', 'naziv' => 'Uvod u kosmologiju', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1317', 'naziv' => 'Osnove biofizike', 'godina' => '3', 'smer_id' => '37'],
            ['predmet_id' => '1318', 'naziv' => 'Mehanik', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1319', 'naziv' => 'Matematika 1', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1320', 'naziv' => 'Programiranje u fizici', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1321', 'naziv' => 'Laboratorijski praktikum 1', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1322', 'naziv' => 'Obnovljivi izvori energije', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1323', 'naziv' => 'Engleski jezik A2', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1324', 'naziv' => 'Termodinamika i molekularna fizika', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1325', 'naziv' => 'Matematika 2', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1326', 'naziv' => 'Metrologija i obrada rezultata merenja', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1327', 'naziv' => 'Laboratorijski praktikum 2', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1328', 'naziv' => 'Hemija', 'godina' => '1', 'smer_id' => '38'],
            ['predmet_id' => '1329', 'naziv' => 'Elektromagnetizam', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1330', 'naziv' => 'Matematika 3', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1331', 'naziv' => 'Osnove matematičke fizike', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1332', 'naziv' => 'Laboratorijski praktikum 3', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1333', 'naziv' => 'Programski paketi u fizici', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1334', 'naziv' => 'Psihologija', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1335', 'naziv' => 'Optika', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1336', 'naziv' => 'Osnove teorijske mehanike', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1337', 'naziv' => 'Laboratorijski praktikum 4', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1338', 'naziv' => 'Osnove biofizike', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1339', 'naziv' => 'Matematika 4', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1340', 'naziv' => 'Matematička fizika', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1341', 'naziv' => 'Osnove računarstva', 'godina' => '2', 'smer_id' => '38'],
            ['predmet_id' => '1342', 'naziv' => 'Osnove atomske i molekularne fizike', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1343', 'naziv' => 'Osnove statističke fizike', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1344', 'naziv' => 'Osnove elektrodinamike', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1345', 'naziv' => 'Oscilacije i talasi', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1346', 'naziv' => 'Pedagogija', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1347', 'naziv' => 'Osnove metodike nastave fizike', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1348', 'naziv' => 'Teorijska mehanika', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1349', 'naziv' => 'Fizički izvori zagađenja životne sredine', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1350', 'naziv' => 'Osnove kvantne mehanike', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1351', 'naziv' => 'Osnove fizike čvrstog stanja', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1352', 'naziv' => 'Eksperimentalne metode u fizici', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1353', 'naziv' => 'Elektrodinamika', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1354', 'naziv' => 'Fizika atmosfere', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1355', 'naziv' => 'Metodika izrade računskih zadataka', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1356', 'naziv' => 'Statistička fizika', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1357', 'naziv' => 'Uvod u kosmologiju', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1358', 'naziv' => 'Automatsko upravljanje', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1359', 'naziv' => 'Stručna praksa', 'godina' => '3', 'smer_id' => '38'],
            ['predmet_id' => '1360', 'naziv' => 'Teorijska mehanika', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1361', 'naziv' => 'Kvantna mehanika', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1362', 'naziv' => 'Elektrodinamika', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1363', 'naziv' => 'Fizička elektronika', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1364', 'naziv' => 'Pedagogija', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1365', 'naziv' => 'Fizička i tehnička merenja', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1366', 'naziv' => 'Opšta teorija relativnosti', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1367', 'naziv' => 'Metodika nastave fizike', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1368', 'naziv' => 'Simetrije u fizici', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1369', 'naziv' => 'Savremene metode eksperimentalne fizike', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1370', 'naziv' => 'Elektronika', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1371', 'naziv' => 'Atomska i molekularna fizika', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1372', 'naziv' => 'Statistička fizika', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1373', 'naziv' => 'Fizika jonizovanih gasova', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1374', 'naziv' => 'Osnove astrofizike', 'godina' => '1', 'smer_id' => '39'],
            ['predmet_id' => '1375', 'naziv' => 'Fizika čvrstog stanja', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1376', 'naziv' => 'Osnove fizike plazme', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1377', 'naziv' => 'Fizika elementarnih čestica', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1378', 'naziv' => 'Nastavna sredstva fizike', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1379', 'naziv' => 'Modelovanje i simulacija fizičkih sistema', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1380', 'naziv' => 'Teorija polјa', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1381', 'naziv' => 'Plazmene i laserske tehnologije', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1382', 'naziv' => 'Fizika u školi', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1383', 'naziv' => 'Radijaciona fizika', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1384', 'naziv' => 'Numeričke metode u fizici', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1385', 'naziv' => 'Uvod u nelinearnu dinamiku', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1386', 'naziv' => 'Istorija i filozofija fizike', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1387', 'naziv' => 'Metodika rešavanja računskih zadataka', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1388', 'naziv' => 'Planetologija', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1389', 'naziv' => 'Interakcija laserskog zračenja sa plazmom', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1390', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1391', 'naziv' => 'Zvezde i zvezdani sistemi', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1392', 'naziv' => 'Uvod u kvantnu optiku', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1393', 'naziv' => 'Fizika lasera', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1394', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1395', 'naziv' => 'Završni rad', 'godina' => '2', 'smer_id' => '39'],
            ['predmet_id' => '1396', 'naziv' => 'Fizička elektronika', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1397', 'naziv' => 'Fizička i tehnička merenja', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1398', 'naziv' => 'Fizika čvrstog stanja', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1399', 'naziv' => 'Osnove energetike', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1400', 'naziv' => 'Teorijska mehanika', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1401', 'naziv' => 'Pedagogija', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1402', 'naziv' => 'Kvantna mehanika', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1403', 'naziv' => 'Numeričke metode u fizici', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1404', 'naziv' => 'Radijaciona fizika', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1405', 'naziv' => 'Elektrodinamika', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1406', 'naziv' => 'Atomska i molekularna fizika', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1407', 'naziv' => 'Elektronika', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1408', 'naziv' => 'Savremene metode eksperimentalne fizike', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1409', 'naziv' => 'Osnove fizike jonizovanih gasova', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1410', 'naziv' => 'Metodika nastave fizike', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1411', 'naziv' => 'Fizika senzora i pretvarača', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1412', 'naziv' => 'Statistička fizika', 'godina' => '1', 'smer_id' => '40'],
            ['predmet_id' => '1413', 'naziv' => 'Fizika površina i tankih slojeva', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1414', 'naziv' => 'Osnove fizike plazme', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1415', 'naziv' => 'Fizika elementarnih čestica', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1416', 'naziv' => 'Modelovanje i simulacija fizičkih sistema', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1417', 'naziv' => 'Automatsko upravlјanje', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1418', 'naziv' => 'Nastavna sredstva fizike', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1419', 'naziv' => 'Plazmene i laserske tehnologije', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1420', 'naziv' => 'Primena plazme u nanotehnologijama', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1421', 'naziv' => 'Nuklearna medicinska fizika', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1422', 'naziv' => 'Fizika u školi', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1423', 'naziv' => 'Fizika materijala', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1424', 'naziv' => 'Fizika i tehnika vakuuma', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1425', 'naziv' => 'Optoelektronika', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1426', 'naziv' => 'Metodika rešavanja računskih zadataka', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1427', 'naziv' => 'Osnove astrofizike', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1428', 'naziv' => 'Fizika lasera', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1429', 'naziv' => 'Sistemi za akviziciju podataka', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1430', 'naziv' => 'Istorija i filozofija fizike', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1431', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1432', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1433', 'naziv' => 'Diplomski rad', 'godina' => '2', 'smer_id' => '40'],
            ['predmet_id' => '1434', 'naziv' => 'Odabrana poglavlјa teorijske fizike', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1435', 'naziv' => 'Numeričke metode u fizici', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1436', 'naziv' => 'Strukture podataka i algoritmi', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1437', 'naziv' => 'Pedagogija', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1438', 'naziv' => 'Fizička i tehnička merenja', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1439', 'naziv' => 'Opšta teorija relativnosti', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1440', 'naziv' => 'Programski paketi u fizici', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1441', 'naziv' => 'Fizika čvrstog stanja', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1442', 'naziv' => 'Kvantna mehanika', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1443', 'naziv' => 'Kvantna informatika', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1444', 'naziv' => 'Elektronika', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1445', 'naziv' => 'Baze podataka', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1446', 'naziv' => 'Odabrana poglavlјa eksperimentalne fizike', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1447', 'naziv' => 'Osnove astrofizike', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1448', 'naziv' => 'Osnove fizike jonizovanih gasova', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1449', 'naziv' => 'Metodika nastave fizike', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1450', 'naziv' => 'Savremene metode eksperimentalne fizike', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1451', 'naziv' => 'Metodika rešavanja računskih zadataka', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1452', 'naziv' => 'Atomska i molekularna fizika', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1453', 'naziv' => 'Fizika senzora i pretvarača', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1454', 'naziv' => 'Statistička fizika', 'godina' => '1', 'smer_id' => '41'],
            ['predmet_id' => '1455', 'naziv' => 'Fizika elementarnih čestica', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1456', 'naziv' => 'Uvod u nelinearnu dinamiku', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1457', 'naziv' => 'Uvod u WEB programiranje', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1458', 'naziv' => 'Nastavna sredstva fizike', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1459', 'naziv' => 'Teorija polјa', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1460', 'naziv' => 'Automatsko upravlјanje', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1461', 'naziv' => 'Fizika u školi', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1462', 'naziv' => 'Modelovanje i simulacija fizičkih sistema', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1463', 'naziv' => 'Radijaciona fizika', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1464', 'naziv' => 'Vizuelna kvantna mehanika', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1465', 'naziv' => 'Softverski praktikum', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1466', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1467', 'naziv' => 'Istorija i filozofija fizike', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1468', 'naziv' => 'Sistemi za akviziciju podataka', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1469', 'naziv' => 'Studijski istraživački rad', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1470', 'naziv' => 'Završni rad', 'godina' => '2', 'smer_id' => '41'],
            ['predmet_id' => '1471', 'naziv' => 'Fizika čvrstog stanja', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1472', 'naziv' => 'Nuklearna fizika', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1473', 'naziv' => 'Fizička elektronika', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1474', 'naziv' => 'Savremene metode eksperimentalne fizike', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1475', 'naziv' => 'Fizika lasera', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1476', 'naziv' => 'Kvantna mehanika', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1477', 'naziv' => 'Numeričke metode u fizici', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1478', 'naziv' => 'Nastavna sredstva fizike 1', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1479', 'naziv' => 'Atomska i molekularna fizika', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1480', 'naziv' => 'Elektronika', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1481', 'naziv' => 'Fizika jonizovanih gasova', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1482', 'naziv' => 'Fizika i tehnika vakuuma', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1483', 'naziv' => 'Modelovanje i simulacija fizičkih sistema', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1484', 'naziv' => 'Istorija i filozofija fizike', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1485', 'naziv' => 'Metodika nastave fizike', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1486', 'naziv' => 'Plazmene i laserske tehnologije', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1487', 'naziv' => 'Osnove energetike', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1488', 'naziv' => 'Astrofizika', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1489', 'naziv' => 'Fizika životne sredine', 'godina' => '1', 'smer_id' => '42'],
            ['predmet_id' => '1490', 'naziv' => 'Fizika materijala', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1491', 'naziv' => 'Fizika senzora i pretvarača', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1492', 'naziv' => 'Osnove fizike plazme', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1493', 'naziv' => 'Fizika površina i tankih slojeva', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1494', 'naziv' => 'Radijaciona fizika', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1495', 'naziv' => 'Optoelektronika', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1496', 'naziv' => 'Osnove fizike elementarnih čestica', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1497', 'naziv' => 'Fizika u školi 1', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1498', 'naziv' => 'Savremeni sistemi za akviziciju podataka', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1499', 'naziv' => 'Primena plazme u industriji i biomedicini', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1500', 'naziv' => 'Nuklearna medicinska fizika', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1501', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1502', 'naziv' => 'Stručna praksa', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1503', 'naziv' => 'Studijsko istraživački rad', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1504', 'naziv' => 'Predmet master rada', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1505', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '42'],
            ['predmet_id' => '1506', 'naziv' => 'Nuklearna fizika', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1507', 'naziv' => 'Fizička elektronika', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1508', 'naziv' => 'Nastavna sredstva fizike 1', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1509', 'naziv' => 'Fizika u školi 1', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1510', 'naziv' => 'Poglavlja teorijske fizike', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1511', 'naziv' => 'Fizika jonizovanih gasova i lasera', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1512', 'naziv' => 'Atomska i molekularna fizika', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1513', 'naziv' => 'Istorija i filozofija fizike', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1514', 'naziv' => 'Metodika nastave fizike', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1515', 'naziv' => 'Nastavna sredstva fizike 2', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1516', 'naziv' => 'Fizika životne sredine', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1517', 'naziv' => 'Modelovanje i simulacija fizičkih sistema', 'godina' => '1', 'smer_id' => '43'],
            ['predmet_id' => '1518', 'naziv' => 'Osnove fizike plazme', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1519', 'naziv' => 'Osnove fizike elementarnih čestica', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1520', 'naziv' => 'Fizika i svakodnevni život', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1521', 'naziv' => 'Radijaciona fizika', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1522', 'naziv' => 'Kvantna mehanika', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1523', 'naziv' => 'Numeričke metode u fizici', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1524', 'naziv' => 'Fizika materijala', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1525', 'naziv' => 'Fizika u školi 2', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1526', 'naziv' => 'Struktura kosmosa na velikim skalama', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1527', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1528', 'naziv' => 'Astrofizika', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1529', 'naziv' => 'Stručna praksa', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1530', 'naziv' => 'Studijsko istraživački rad', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1531', 'naziv' => 'Predmet master rada', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1532', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '43'],
            ['predmet_id' => '1533', 'naziv' => 'Kvantna mehanika', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1534', 'naziv' => 'Nuklearna fizika', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1535', 'naziv' => 'Fizička elektronika', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1536', 'naziv' => 'Fizika čvrstog stanja', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1537', 'naziv' => 'Fizika i svakodnevni život', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1538', 'naziv' => 'Fizika u školi 1', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1539', 'naziv' => 'Poglavlja teorijske fizike', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1540', 'naziv' => 'Numeričke metode u fizici', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1541', 'naziv' => 'Nastavna sredstva fizike 1', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1542', 'naziv' => 'Fizika jonizovanih gasova i lasera', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1543', 'naziv' => 'Teorija polja', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1544', 'naziv' => 'Atomska i molekularna fizika', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1545', 'naziv' => 'Astrofizika', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1546', 'naziv' => 'Istorija i filozofija fizike', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1547', 'naziv' => 'Uvod u nelinearnu optiku', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1548', 'naziv' => 'Elektronika', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1549', 'naziv' => 'Fizika životne sredine', 'godina' => '1', 'smer_id' => '44'],
            ['predmet_id' => '1550', 'naziv' => 'Osnove fizike plazme', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1551', 'naziv' => 'Uvod u kvantnu optiku', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1552', 'naziv' => 'Teorija čestica', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1553', 'naziv' => 'Fizika u školi 2', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1554', 'naziv' => 'Struktura kosmosa na velikim skalama', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1555', 'naziv' => 'Teorija relativnosti', 'godina' => '2', 'smer_id' => '44'],
            ['predmet_id' => '1556', 'naziv' => 'Uvod u nelinearnu dinamiku', 'godina' => '2', 'smer_id' => '44'],
        ]);
    }
}
