<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PredmetSeeder1 extends Seeder
{
    public function run(): void
    {
        DB::table('predmet')->insert([
            ['predmet_id' => '1', 'naziv' => 'Opsta i neorganska hemija', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '2', 'naziv' => 'Fizika', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '3', 'naziv' => 'Osnovi informatike', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '4', 'naziv' => 'Morfologija i anatomija bilјaka', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '5', 'naziv' => 'Zoologija beskicmenjaka 1', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '6', 'naziv' => 'Organska hemija', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '7', 'naziv' => 'Biologija celije', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '8', 'naziv' => 'Verovatnoca i statistika u biologiji', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '9', 'naziv' => 'Zoologija beskicmenjaka 2', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '10', 'naziv' => 'Engleski jezik 1', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '11', 'naziv' => 'Istorija i filozofija biologije', 'godina' => '1', 'smer_id' => '1'],
            ['predmet_id' => '12', 'naziv' => 'Mikrobiologija', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '13', 'naziv' => 'Zoologija kicmenjaka', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '14', 'naziv' => 'Biohemija', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '15', 'naziv' => 'Algologija i mikologija', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '16', 'naziv' => 'Principi laboratorijskog rada u biologiji', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '17', 'naziv' => 'Pedagogija', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '18', 'naziv' => 'Razvice zivotinja', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '19', 'naziv' => 'Sistematika i filogenija bilјaka', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '20', 'naziv' => 'Opsta ekologija', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '21', 'naziv' => 'Istorijska geologija', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '22', 'naziv' => 'Psihologija', 'godina' => '2', 'smer_id' => '1'],
            ['predmet_id' => '23', 'naziv' => 'Genetika', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '24', 'naziv' => 'Fiziologija bilјaka', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '25', 'naziv' => 'Fiziologija zivotinja', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '26', 'naziv' => 'Biogeografija', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '27', 'naziv' => 'Laboratorijske zivotinje u bioloskim istrazivanjima', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '28', 'naziv' => 'Biologija coveka', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '29', 'naziv' => 'Imunobiologija', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '30', 'naziv' => 'Osnovi ekologije bilјaka', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '31', 'naziv' => 'Osnovi ekologije zivotinja', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '32', 'naziv' => 'Molekularna biologija', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '33', 'naziv' => 'Organska evolucija', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '34', 'naziv' => 'Metodika nastave biologije', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '35', 'naziv' => 'Osnovi konzervacione biologije', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '36', 'naziv' => 'Osnovi astrofizike SA astrobiologijom', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '37', 'naziv' => 'Matematika u biologiji', 'godina' => '3', 'smer_id' => '1'],
            ['predmet_id' => '38', 'naziv' => 'Hemija', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '39', 'naziv' => 'Fizika za biologe', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '40', 'naziv' => 'Morfologija i anatomija biljaka', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '41', 'naziv' => 'Zoologija beskicmenjaka 1', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '42', 'naziv' => 'Istorija i filozofija biologije', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '43', 'naziv' => 'Engleski jezik A2', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '44', 'naziv' => 'Biologija celije', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '45', 'naziv' => 'Zoologija beskicmenjaka', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '46', 'naziv' => 'Algologija i mikologija', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '47', 'naziv' => 'Bioloska raznovrsnost', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '48', 'naziv' => 'Osnovi astrobiologije', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '49', 'naziv' => 'Engleski jezik B1', 'godina' => '1', 'smer_id' => '2'],
            ['predmet_id' => '50', 'naziv' => 'Mikrobiologija', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '51', 'naziv' => 'Anatomija i morfologija hordata', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '52', 'naziv' => 'Biohemija', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '53', 'naziv' => 'Razvice zivotinja', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '54', 'naziv' => 'Istorijska geologija', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '55', 'naziv' => 'Psihologija', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '56', 'naziv' => 'Sistematika i filogenija biljaka', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '57', 'naziv' => 'Sistematika i filogenija hordata', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '58', 'naziv' => 'Molekularna biologija', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '59', 'naziv' => 'Opsta ekologija', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '60', 'naziv' => 'Terenska istrazivanja u biologiji 1', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '61', 'naziv' => 'Principi laboratorijskog rada u biologiji', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '62', 'naziv' => 'Parazitologija', 'godina' => '2', 'smer_id' => '2'],
            ['predmet_id' => '63', 'naziv' => 'Principi genetike', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '64', 'naziv' => 'Fiziologija biljaka', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '65', 'naziv' => 'Fiziologija 1', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '66', 'naziv' => 'Statistika u biologiji', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '67', 'naziv' => 'Laboratorijske zivotinje u bioloskim istrazivanjima', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '68', 'naziv' => 'Pedagogija', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '69', 'naziv' => 'Biogeografija', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '70', 'naziv' => 'Fiziologija 2', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '71', 'naziv' => 'Instrumentalne metode u biologiji', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '72', 'naziv' => 'Organska evolucija', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '73', 'naziv' => 'Metodika nastave biologije', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '74', 'naziv' => 'Osnove konzervacione biologije ', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '75', 'naziv' => 'Terenska istrazivanja u biologiji 2', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '76', 'naziv' => 'Strucna praksa', 'godina' => '3', 'smer_id' => '2'],
            ['predmet_id' => '77', 'naziv' => 'Ekologija bilјaka', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '78', 'naziv' => 'Zastita zivotne sredine', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '79', 'naziv' => 'Uporedna fiziologija zivotinja', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '80', 'naziv' => 'Metodologija eksperimentalnog rada u biologiji', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '81', 'naziv' => 'Sistematika i ekologija lekovitih bilјaka', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '82', 'naziv' => 'Bioloske simbioze', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '83', 'naziv' => 'Mikrobioloski praktikum', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '84', 'naziv' => 'Strukturne adaptacije bilјaka', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '85', 'naziv' => 'Ćelijska fiziologija', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '86', 'naziv' => 'Biohemijska sistematika bilјaka', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '87', 'naziv' => 'Ekologija zivotinja', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '88', 'naziv' => 'Teorija evolucije', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '89', 'naziv' => 'Fiziologija stresa kod bilјaka', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '90', 'naziv' => 'Humana genetika', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '91', 'naziv' => 'Forenzicka biologija', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '92', 'naziv' => 'Metodika prakticne nastave biologije u skolama', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '93', 'naziv' => 'Kultura bilјnih celija', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '94', 'naziv' => 'Kultura zivotinjskih celija', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '95', 'naziv' => 'Botanicki praktikum', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '96', 'naziv' => 'Fitogeografija', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '97', 'naziv' => 'Entomologija', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '98', 'naziv' => 'Zoogeografija', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '99', 'naziv' => 'Osnovi genetskog inzenjerstva', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '100', 'naziv' => 'Eksperimentalna hematologija', 'godina' => '1', 'smer_id' => '3'],
            ['predmet_id' => '101', 'naziv' => 'Metodologija naucno-istrazivackog rada', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '102', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '103', 'naziv' => 'Biotehnologija', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '104', 'naziv' => 'Zooloski praktikum', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '105', 'naziv' => 'Didakticke inovacije', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '106', 'naziv' => 'Eksperimentalna biohemija', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '107', 'naziv' => 'Medicinska mikrobiologija', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '108', 'naziv' => 'Bioloska antropologija', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '109', 'naziv' => 'Studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '110', 'naziv' => 'Master rad', 'godina' => '2', 'smer_id' => '3'],
            ['predmet_id' => '111', 'naziv' => 'Ekologija bilјaka', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '112', 'naziv' => 'Bioindikacije i biomonitoring', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '113', 'naziv' => 'Ekotoksikologija', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '114', 'naziv' => 'Genotoksikologija', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '115', 'naziv' => 'Hemija zivotne sredine', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '116', 'naziv' => 'Limnologija', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '117', 'naziv' => 'Ekologija zivotinja', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '118', 'naziv' => 'Hidrobiologija', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '119', 'naziv' => 'Fitogeografija', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '120', 'naziv' => 'Zoogeografija', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '121', 'naziv' => 'Zasticene vrste i podrucja Srbije', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '122', 'naziv' => 'Abioticka svojstva vodenih ekosistema', 'godina' => '1', 'smer_id' => '4'],
            ['predmet_id' => '123', 'naziv' => 'Metodologija naučno-istrazivackog rada', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '124', 'naziv' => 'Konzervaciona biologija', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '125', 'naziv' => 'Zastita bioloske raznovrnosti', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '126', 'naziv' => 'Vegetacija sveta', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '127', 'naziv' => 'Globalna ekologija', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '128', 'naziv' => 'Ekologija mikroorganizama', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '129', 'naziv' => 'Urbana ekologija', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '130', 'naziv' => 'Studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '131', 'naziv' => 'Terenska istrazivanja u ekologiji', 'godina' => '2', 'smer_id' => '4'],
            ['predmet_id' => '132', 'naziv' => 'Metodologija naucno-istrazivackog rada', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '133', 'naziv' => 'Ekologija biljaka', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '134', 'naziv' => 'Fiziologija rastenja i razvica biljaka', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '135', 'naziv' => 'Botanicki praktikum', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '136', 'naziv' => 'Mikrobiologija hrane', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '137', 'naziv' => 'Eksperimentalna biohemija', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '138', 'naziv' => 'Fitogeografija', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '139', 'naziv' => 'Zoogeografija', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '140', 'naziv' => 'Biologija coveka', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '141', 'naziv' => 'Ekologija zivotinja', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '142', 'naziv' => 'Genetika', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '143', 'naziv' => 'Strukturna adaptacija biljaka', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '144', 'naziv' => 'Fiziologija stresa kod biljaka', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '145', 'naziv' => 'Bioloske simbioze', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '146', 'naziv' => 'Imunobiologija', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '147', 'naziv' => 'Lekovite biljke', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '148', 'naziv' => 'Entomologija', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '149', 'naziv' => 'Pedagoska komunikacija', 'godina' => '1', 'smer_id' => '5'],
            ['predmet_id' => '150', 'naziv' => 'Teorija organske evolucije', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '151', 'naziv' => 'Zastita zivotne sredine', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '152', 'naziv' => 'Biohemijska sistematika biljaka', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '153', 'naziv' => 'Medicinska mikrobiologija', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '154', 'naziv' => 'Osnovi biotehnologije', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '155', 'naziv' => 'Metode prakticne nastave biologije u skolama', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '156', 'naziv' => 'Metode eksperimentalnog rada u biologiji', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '157', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '158', 'naziv' => 'Genotoksikologija', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '159', 'naziv' => 'Bioloska antropologija', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '160', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '161', 'naziv' => 'Predmet zavrsnog rada', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '162', 'naziv' => 'Zavrsni rad', 'godina' => '2', 'smer_id' => '5'],
            ['predmet_id' => '163', 'naziv' => 'Ekologija biljaka', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '164', 'naziv' => 'Zastita bioloske raznovrsnosti', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '165', 'naziv' => 'Abioticka svosjtva vodenih ekosistema', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '166', 'naziv' => 'Hemija zivotne sredine', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '167', 'naziv' => 'Numericka ekologija', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '168', 'naziv' => 'Metodologija naucno-istrazivackog rada', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '169', 'naziv' => 'Ekotoksikologija', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '170', 'naziv' => 'Biologija i ekologija lisaja', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '171', 'naziv' => 'Bioindikacije i biomonitoring', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '172', 'naziv' => 'Ekologija zivotinja', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '173', 'naziv' => 'Hidrobiologija', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '174', 'naziv' => 'Metodologija indetifikacije i kartiranje stan', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '175', 'naziv' => 'Zasticene vrste i podrucja Srbije', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '176', 'naziv' => 'Ekologija vlaznih i riparijalnih stanista', 'godina' => '1', 'smer_id' => '6'],
            ['predmet_id' => '177', 'naziv' => 'Konzervaciona biologija', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '178', 'naziv' => 'Fitogeografija', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '179', 'naziv' => 'Zoogeografija', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '180', 'naziv' => 'Ekologija mikroorganizama', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '181', 'naziv' => 'Fitoremedijacija', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '182', 'naziv' => 'Vegetacija sveta', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '183', 'naziv' => 'Terenska istrazivanja u ekologiji', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '184', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '185', 'naziv' => 'Predmet zavrsnog rada', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '186', 'naziv' => 'Zavrsni rad', 'godina' => '2', 'smer_id' => '6'],
            ['predmet_id' => '187', 'naziv' => 'Metodologija naucno-istrazivackog rada', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '188', 'naziv' => 'Molekularna biologija prokariota', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '189', 'naziv' => 'Molekularna genetika', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '190', 'naziv' => 'Kultura biljnih celija', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '191', 'naziv' => 'Eksperimentalna molekularna biologija', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '192', 'naziv' => 'Forenzicka biologija', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '193', 'naziv' => 'Eksperimentalna hematologija', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '194', 'naziv' => 'Biologija coveka', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '195', 'naziv' => 'Molekularna biologija eukariota', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '196', 'naziv' => 'Molekularna biologija i biotehnologija biljaka', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '197', 'naziv' => 'Endokrinologija', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '198', 'naziv' => 'Molekularna sistematika', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '199', 'naziv' => 'Humana genetika', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '200', 'naziv' => 'Osnovi genetickog inzinjerstva i biotehnologija', 'godina' => '1', 'smer_id' => '7'],
            ['predmet_id' => '201', 'naziv' => 'Teorija organske evolucije', 'godina' => '2', 'smer_id' => '7'],
            ['predmet_id' => '202', 'naziv' => 'Biotehnologija', 'godina' => '2', 'smer_id' => '7'],
            ['predmet_id' => '203', 'naziv' => 'Biohemija i fiziologija mikroorganizama', 'godina' => '2', 'smer_id' => '7'],
            ['predmet_id' => '204', 'naziv' => 'Ekofiziologija', 'godina' => '2', 'smer_id' => '7'],
            ['predmet_id' => '205', 'naziv' => 'Ekofiziologija', 'godina' => '2', 'smer_id' => '7'],
            ['predmet_id' => '206', 'naziv' => 'Molekulrana evolucija', 'godina' => '2', 'smer_id' => '7'],
            ['predmet_id' => '207', 'naziv' => 'Osnovi bioinformatike', 'godina' => '2', 'smer_id' => '7'],
            ['predmet_id' => '208', 'naziv' => 'Kvantitativna biologija', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '209', 'naziv' => 'Molekularna biologija celije', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '210', 'naziv' => 'Opšte i molekularne metode u mikrobiologiji', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '211', 'naziv' => 'Koncepti konzervacionog planiranja', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '212', 'naziv' => 'Raznovrsnost vaskularne flore Balkanskog poluostrva', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '213', 'naziv' => 'Humana i medicinska genetika', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '214', 'naziv' => 'Visi kurs fiziologije zivotinja', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '215', 'naziv' => 'Genomika', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '216', 'naziv' => 'Fiziologija rastenja i razvica biljaka', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '217', 'naziv' => 'Sekundarni metaboliti odabranog biljnog taksona', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '218', 'naziv' => 'Mikroorganizmi u biotehnologiji', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '219', 'naziv' => 'Patogeni mikroorganizmi i gljive', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '220', 'naziv' => 'Bioloska kontrola stetnih insekata', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '221', 'naziv' => 'Primenjena biologija i ekologija odabranog taksona', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '222', 'naziv' => 'Ekologija kavernikolnih organizama', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '223', 'naziv' => 'Sistematika i filogenija odabranog biljnog taksona', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '224', 'naziv' => 'Anatomija odabranog biljnog taksona', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '225', 'naziv' => 'Metodologija istraživanja slatkovodnih makroinvertebrata', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '226', 'naziv' => 'Ekologija odabranog biljnog taksona', 'godina' => '1', 'smer_id' => '8'],
            ['predmet_id' => '227', 'naziv' => 'Tkivno inzenjerstvo', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '228', 'naziv' => 'Biologija maticnih celija', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '229', 'naziv' => 'Molekularna biologija maligne celije', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '230', 'naziv' => 'Molekularna genetika mikroorganizama', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '231', 'naziv' => 'Biohemija i fiziologija mikroorganizama', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '232', 'naziv' => 'Toksini mikroorganizama', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '233', 'naziv' => 'Ugrozene i endemicne vrste biljaka u kulturi ', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '234', 'naziv' => 'Metodologija geobotanickih istrazivanja', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '235', 'naziv' => 'Sistematika i filogenija odabranog životinjskog taksona', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '236', 'naziv' => 'Kvantitativna konzervaciona ekologija', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '237', 'naziv' => 'Monitoring slatkovodnih ekosistema', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '238', 'naziv' => 'Biljne zajednice i stanista Balkanskog poluostrva', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '239', 'naziv' => 'Biologija invazivnih biljnih taksona', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '240', 'naziv' => 'Bioindikacije i biomonitoring odabranog habitata', 'godina' => '2', 'smer_id' => '8'],
            ['predmet_id' => '241', 'naziv' => 'Kvantativna biologija', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '242', 'naziv' => 'Sistematika i filogenija odabranog životinjskog taksona', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '243', 'naziv' => 'Flora i vegetacija Balkanskog poluostrva', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '244', 'naziv' => 'Opste i molekularne metode u mikrobiologiji', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '245', 'naziv' => 'Molekularna biologija celije', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '246', 'naziv' => 'Imunski odgovor u patoloskim stanjima', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '247', 'naziv' => 'Sistematika i filogenija odabranog biljnog taksona', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '248', 'naziv' => 'Geneticko inzenjerstvo i biotehnologija biljaka', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '249', 'naziv' => 'Visi kurs fiziologije zivotinja', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '250', 'naziv' => 'Biologija maticnih celija', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '251', 'naziv' => 'Bioindikacije i biomonitoring odabranog habitata', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '252', 'naziv' => 'Predmet doktorske disertacije 1', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '253', 'naziv' => 'Koncepti konzervacionog planiranja', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '254', 'naziv' => 'Ekologija odabranog biljnog taksona', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '255', 'naziv' => 'Fiziologija mikroorganizama', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '256', 'naziv' => 'Geometrijska morfometrija u biologiji', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '257', 'naziv' => 'Patogeni mikroorganizmi i gljive', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '258', 'naziv' => 'Sekundarni metaboliti odabranog biljnog taksona', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '259', 'naziv' => 'Primenjena biologija i ekologija odabranog taksona', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '260', 'naziv' => 'Anatomija odabranog biljnog taksona', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '261', 'naziv' => 'Monitoring slatkovodnih ekosistema', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '262', 'naziv' => 'Oksidativni stres i mehanizmi antioksidativine zaštite', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '263', 'naziv' => 'Sekundarni metaboliti u kulturi biljnih tkiva in vitro', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '264', 'naziv' => 'Genomika', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '265', 'naziv' => 'Predmet doktorske disertacije 2', 'godina' => '1', 'smer_id' => '9'],
            ['predmet_id' => '266', 'naziv' => 'Bioloska kontrola', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '267', 'naziv' => 'Tkivno inzenjerstvo', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '268', 'naziv' => 'Molekularna biologija maligne celije', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '269', 'naziv' => 'Mikroorganizmi u biotehnologiji ', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '270', 'naziv' => 'Molekularna sistematika zivotinja', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '271', 'naziv' => 'Metodologija geobotanickih istrazivanja', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '272', 'naziv' => 'Kvantitativna konzervaciona ekologija', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '273', 'naziv' => 'Ekologija kavernikolnih organizama', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '274', 'naziv' => 'Ekologija riba', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '275', 'naziv' => 'Vaskularne biljke vodenih ekosistema', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '276', 'naziv' => 'Ugrozene i endemicne vrste biljaka u kulturi ', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '277', 'naziv' => 'Etnobotanika ', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '278', 'naziv' => 'Predmet doktorske disertacije 3', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '279', 'naziv' => 'Molekularna sistematika biljaka', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '280', 'naziv' => 'Metodologija istrazivanja slatkovodnih', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '281', 'naziv' => 'Sukcesija biljnih zajednica ', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '282', 'naziv' => 'Biologija invazivnih biljnih taksona', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '283', 'naziv' => 'Fitohormoni', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '284', 'naziv' => 'Ekologija kopnenih voda', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '285', 'naziv' => 'Morfometrija u botanici', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '286', 'naziv' => 'Molekularne osnove humanih bolesti ', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '287', 'naziv' => 'Analiza podataka u fitocenologiji', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '288', 'naziv' => 'Herpetologija', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '289', 'naziv' => 'Molekularna genetika mikroorganizama ', 'godina' => '2', 'smer_id' => '9'],
            ['predmet_id' => '290', 'naziv' => 'Uvod u geografiju', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '291', 'naziv' => 'Matematicka geografija', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '292', 'naziv' => 'Geologija sa petrografijom', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '293', 'naziv' => 'Nacionalna ekonomija', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '294', 'naziv' => 'Geometrija', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '295', 'naziv' => 'Poslovna matematika', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '296', 'naziv' => 'Kartografija', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '297', 'naziv' => 'Geoloski resursi', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '298', 'naziv' => 'Informatika', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '299', 'naziv' => 'Engleski jezik', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '300', 'naziv' => 'Fizika', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '301', 'naziv' => 'Francuski jezik', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '302', 'naziv' => 'Prakticna nastava 1 ', 'godina' => '1', 'smer_id' => '10'],
            ['predmet_id' => '303', 'naziv' => 'Klimatologija', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '304', 'naziv' => 'Biogeografija', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '305', 'naziv' => 'Geografija stanovnistva', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '306', 'naziv' => 'Geografija zemlјista', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '307', 'naziv' => 'Pedagogija', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '308', 'naziv' => 'Geografija lokalne sredine', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '309', 'naziv' => 'Hidrologija', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '310', 'naziv' => 'Geomorfologija', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '311', 'naziv' => 'Geografija naselјa', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '312', 'naziv' => 'Statistika', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '313', 'naziv' => 'Geohemija', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '314', 'naziv' => 'Prakticna nastava 2', 'godina' => '2', 'smer_id' => '10'],
            ['predmet_id' => '315', 'naziv' => 'Metodika nastave geografije', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '316', 'naziv' => 'Industrijska geografija', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '317', 'naziv' => 'Geografija Srbije I', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '318', 'naziv' => 'Nacionalna hidrologija', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '319', 'naziv' => 'Nacionalna istorija', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '320', 'naziv' => 'Regionalna geografija I', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '321', 'naziv' => 'Turisticka geografija', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '322', 'naziv' => 'Poslovna statistika', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '323', 'naziv' => 'Kulturno-istorijske osnove turizma', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '324', 'naziv' => 'Nacionalna klimatologija', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '325', 'naziv' => 'Regionalna geografija II', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '326', 'naziv' => 'Geografija Srbije II', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '327', 'naziv' => 'Metodika prakticne nastave geografije', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '328', 'naziv' => 'Agrarna geografija', 'godina' => '3', 'smer_id' => '10'],
            ['predmet_id' => '329', 'naziv' => 'Uvod u geografiju', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '330', 'naziv' => 'Geologija sa paleogeografijom', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '331', 'naziv' => 'Engleski jezik A2', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '332', 'naziv' => 'Osnove fizicke geografije', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '334', 'naziv' => 'Kartografija', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '335', 'naziv' => 'Psihologija', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '336', 'naziv' => 'Francuski jezik 1', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '337', 'naziv' => 'Kulturno-istorijske osnove turizma', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '338', 'naziv' => 'Geografski informacioni sistemi', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '339', 'naziv' => 'Matematicka geografija', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '340', 'naziv' => 'Terenska nastava 1', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '341', 'naziv' => 'Zastita zivotne sredine', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '342', 'naziv' => 'Uvod u statistiku', 'godina' => '1', 'smer_id' => '11'],
            ['predmet_id' => '343', 'naziv' => 'Klimatologija', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '344', 'naziv' => 'Hidrologija', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '345', 'naziv' => 'Biogeografija', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '346', 'naziv' => 'Geografija civilizacija', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '347', 'naziv' => 'Informatika', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '348', 'naziv' => 'Tektonska geomorfologija', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '349', 'naziv' => 'Geonasledje Srbije', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '350', 'naziv' => 'Nacionalni parkovi sveta', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '351', 'naziv' => 'Erozivna geomorfologija', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '352', 'naziv' => 'Pedagogija', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '353', 'naziv' => 'Geografija zemljista sa osnovama pedagogije', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '354', 'naziv' => 'Terenska nastava 2', 'godina' => '2', 'smer_id' => '11'],
            ['predmet_id' => '355', 'naziv' => 'Geografija Srbije', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '356', 'naziv' => 'Klimatske promene', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '357', 'naziv' => 'Koriscenje i zastita voda', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '358', 'naziv' => 'Regionalna geografija 1', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '359', 'naziv' => 'Demogeografija', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '360', 'naziv' => 'Metodika nastave geografije', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '361', 'naziv' => 'Školska praksa', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '362', 'naziv' => 'Regionalna geografija 2', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '363', 'naziv' => 'Turisticka geografija', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '364', 'naziv' => 'Metodika prakticne nastave geografije', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '365', 'naziv' => 'Geografija nastave geografije', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '366', 'naziv' => 'Geografija naselja', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '367', 'naziv' => 'Demografske analize i modeli', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '368', 'naziv' => 'Zagadjujuce supstancije u zemljistu', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '369', 'naziv' => 'Strucna praksa', 'godina' => '3', 'smer_id' => '11'],
            ['predmet_id' => '370', 'naziv' => 'Prostorno planiranje', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '371', 'naziv' => 'Turisticko-geografske regije sveta', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '372', 'naziv' => 'Didakticke inovacije', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '373', 'naziv' => 'Zastita zivotne sredine', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '374', 'naziv' => 'Astronomija', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '375', 'naziv' => 'Nacionalni parkovi', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '376', 'naziv' => 'Tematsko kartiranje', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '377', 'naziv' => 'Politicka geografija', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '378', 'naziv' => 'Stanovnistvo sveta', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '379', 'naziv' => 'Svetska privreda', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '380', 'naziv' => 'Nastavne strategije u izucavanju geografije', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '381', 'naziv' => 'Prakticna nastava', 'godina' => '1', 'smer_id' => '12'],
            ['predmet_id' => '382', 'naziv' => 'Psihologija', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '383', 'naziv' => 'Regionalna geografija Srbije I', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '384', 'naziv' => 'Nacionalna turisticka geografija', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '385', 'naziv' => 'Engleski jezik II', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '386', 'naziv' => 'Urbana ekologija', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '387', 'naziv' => 'Kulturno-istorijske osnove Srbije', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '388', 'naziv' => 'Regionalna geografija Balkanskog poluostrva', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '389', 'naziv' => 'Fizika okoline', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '390', 'naziv' => 'Metodologija naucno-istrazivackog rada', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '391', 'naziv' => 'GIS', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '392', 'naziv' => 'Studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '393', 'naziv' => 'Regionalna geografija Srbije 2', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '394', 'naziv' => 'Zavrsni rad', 'godina' => '2', 'smer_id' => '12'],
            ['predmet_id' => '395', 'naziv' => 'Uvod u ekonomiju', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '396', 'naziv' => 'Osnove turizma', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '397', 'naziv' => 'Geografija turistickih naselјa', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '398', 'naziv' => 'Engleski jezik 2', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '399', 'naziv' => 'Ekonomika i organizacija preduzeca', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '400', 'naziv' => 'Francuski jezik 2', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '401', 'naziv' => 'Ekonomika turizma', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '402', 'naziv' => 'Turisticko uredjenje prostora', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '403', 'naziv' => 'Banjski turizam', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '404', 'naziv' => 'Nacionalni parkovi', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '405', 'naziv' => 'Hotelijerstvo', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '406', 'naziv' => 'Kulturno istorijske osnove Srbije', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '407', 'naziv' => 'Fizika okoline', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '408', 'naziv' => 'Prakticna nastava', 'godina' => '1', 'smer_id' => '13'],
            ['predmet_id' => '409', 'naziv' => 'Menadzment turisticke privrede', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '410', 'naziv' => 'Turisticke agencije i turoperatori', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '411', 'naziv' => 'Urbana ekologija', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '412', 'naziv' => 'Ruralna ekologija', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '413', 'naziv' => 'Tematsko kartiranje', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '414', 'naziv' => 'Menadzment i marketing turisticke destinacije', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '415', 'naziv' => 'Turisticko-geografske regije sveta', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '416', 'naziv' => 'Turizam i zastita zivotne sredine', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '417', 'naziv' => 'GIS', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '418', 'naziv' => 'Nacionalna turisticka geografija', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '419', 'naziv' => 'Metodologija NIR-a', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '420', 'naziv' => 'Ljudski resursi u turizmu', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '421', 'naziv' => 'Studijski istrazivacki rad', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '422', 'naziv' => 'Zavrsni rad', 'godina' => '2', 'smer_id' => '13'],
            ['predmet_id' => '423', 'naziv' => 'Geografske osnove prostornog planiranja', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '424', 'naziv' => 'Hazardi', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '425', 'naziv' => 'Primenjena klimatologija', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '426', 'naziv' => 'Industrijska geografija', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '427', 'naziv' => 'Zasticena prirodna dobra', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '428', 'naziv' => 'Metodologija naucno-istrazivackog rada', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '429', 'naziv' => 'Saobracajna geografija', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '430', 'naziv' => 'Statisticki modeli u geografiji', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '431', 'naziv' => 'Tematsko kartiranje', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '432', 'naziv' => 'Politicka geografija', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '433', 'naziv' => 'Metodicke inovacije u geografiji', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '434', 'naziv' => 'Agrarna geografija', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '435', 'naziv' => 'Geohemija', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '436', 'naziv' => 'Engleski jezik B1', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '437', 'naziv' => 'Terenska nastava', 'godina' => '1', 'smer_id' => '14'],
            ['predmet_id' => '438', 'naziv' => 'Regionalna geografija Srbije 1', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '439', 'naziv' => 'Ruralno planiranje', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '440', 'naziv' => 'Svetska privreda', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '441', 'naziv' => 'Primenjena hidrologija', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '442', 'naziv' => 'Urbana ekologija', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '443', 'naziv' => 'Ruralna ekologija', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '444', 'naziv' => 'Analiza geoprostornih podataka u GIS-u', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '445', 'naziv' => 'Školska praksa', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '446', 'naziv' => 'Studijsko istrazivacki rad', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '447', 'naziv' => 'Regionalna geografija Balkanskog poluostrva', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '448', 'naziv' => 'Regionalna geografija Srbije 2', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '449', 'naziv' => 'Obrazovanje dece sa smetnjama i teskocama u razvoju', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '450', 'naziv' => 'Pedagoska komunikacija', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '451', 'naziv' => 'Predmet zavrsnog rada', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '452', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '453', 'naziv' => 'Zavrsni rad', 'godina' => '2', 'smer_id' => '14'],
            ['predmet_id' => '454', 'naziv' => 'Ekonomika turizma', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '455', 'naziv' => 'Ekoturizam', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '456', 'naziv' => 'Francuski jezik 2', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '457', 'naziv' => 'Osnove turizma', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '458', 'naziv' => 'Turisticko-geografske regije Evrope', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '459', 'naziv' => 'Informacione tehnologije u turizmu', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '460', 'naziv' => 'Poslovna ekonomija', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '461', 'naziv' => 'Hotelijerstvo', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '462', 'naziv' => 'Turisticke regije Srbije', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '463', 'naziv' => 'Engleski jezik B1', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '464', 'naziv' => 'Kulturno-istorijske osnove turizma Srbije', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '465', 'naziv' => 'Gradski turizam', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '466', 'naziv' => 'Turizam i odrzivi razvoj', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '467', 'naziv' => 'Kvantitativno-kvalitativne metode istrazivanja', 'godina' => '1', 'smer_id' => '15'],
            ['predmet_id' => '468', 'naziv' => 'Menadzment i marketing u turizmu', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '469', 'naziv' => 'Menadzment u hotelijerstvu', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '470', 'naziv' => 'Turisticko-geografske regije vanevropskih prostora', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '471', 'naziv' => 'Turisticke agencije i turoperatori', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '472', 'naziv' => 'Klimatske promene i turizam', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '473', 'naziv' => 'Metodika nastave turizma', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '474', 'naziv' => 'Planiranje i uredjenje turistickih prostora', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '475', 'naziv' => 'Tematsko kartiranje', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '476', 'naziv' => 'Analiza geoprostornih podataka u GIS-u', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '477', 'naziv' => 'Turizam Srbije', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '478', 'naziv' => 'Studijsko istrazivacki rad', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '479', 'naziv' => 'Banjski i planinski turizam', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '480', 'naziv' => 'Sportski turizam i rekreacija', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '481', 'naziv' => 'Strucna praksa', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '482', 'naziv' => 'Predmet zavrsnog rada', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '483', 'naziv' => 'Zavrsni rad', 'godina' => '2', 'smer_id' => '15'],
            ['predmet_id' => '484', 'naziv' => 'Naucne metode, istrazivanje i pisanje naucnog rada', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '485', 'naziv' => 'Primena GIS-a i daljinske detekcije u istrazi', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '486', 'naziv' => 'Fizicko-geografski procesi', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '487', 'naziv' => 'Kvalitativna i kvantitativna istrazivanja u fizičkoj geografiji', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '488', 'naziv' => 'Matematicko statisticke metode u geografiji i turizmu', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '489', 'naziv' => 'Savremeni demografski problemi i procesi', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '490', 'naziv' => 'Tipologija i tipovi regija', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '491', 'naziv' => 'Odrzivi razvoj i odrzivi turizam', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '492', 'naziv' => 'Evropske integracije i zastita zivotne sredine', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '493', 'naziv' => 'Kartografska vizuelizacija prirodnih i drustvenih potencijala', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '494', 'naziv' => 'Problemi savremene klimatologije', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '495', 'naziv' => 'Teorijsko metodoloske osnove geografskih istraživanja naselja', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '496', 'naziv' => 'Upravljanje i valorizacija turistickih resursa', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '497', 'naziv' => 'Geoekologija Zemlje', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '498', 'naziv' => 'Faktori konkurentnosti prirodnih i kulturnih ', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '499', 'naziv' => 'Odrzivo upravljanje vodama', 'godina' => '1', 'smer_id' => '16'],
            ['predmet_id' => '500', 'naziv' => 'Lokalni i regionalni razvoj', 'godina' => '2', 'smer_id' => '16'],
            ['predmet_id' => '501', 'naziv' => 'Standardi postignuca u nastavi geografije', 'godina' => '2', 'smer_id' => '16'],
        ]);
    }
}
